## Load Data

In [2]:
import json
import pandas as pd

with open('../restaurants.menu_item_variations.json', 'r') as file:
    item_list = json.load(file)
file.close()

## Select all Items for Specific Restaurants: Chick-fil-A, Taco Bell, and Chipotle

In [3]:
chick_fil_a_items = []
tacobell_items = []
chipotle_items = []

for item in item_list:
    if item.get("restaurant_name") == "Chick-fil-A":
        chick_fil_a_items.append(item)

    elif item.get("restaurant_name") == "Taco Bell":
        tacobell_items.append(item)
    
    elif item.get("restaurant_name") == "Chipotle":
        chipotle_items.append(item)

print(f"Number of Chick-fil-A items: {len(chick_fil_a_items)}")
print(f"Number of Taco Bell items: {len(tacobell_items)}")
print(f"Number of Chipotle items: {len(chipotle_items)}")

# making dataframes just to visualize easier
df_cfa = pd.DataFrame(chick_fil_a_items)
df_tb = pd.DataFrame(tacobell_items)
df_chipotle = pd.DataFrame(chipotle_items)

Number of Chick-fil-A items: 177
Number of Taco Bell items: 205
Number of Chipotle items: 99

### Visualization

In [ ]:
# Chick fil A items
df_cfa.head()

,item_id,menu_item_id,menu_item_name,restaurant_name,cuisine_type,macronutrient_profile,recipe_items,price,golden_ratio,ai_description,category,allergen_info,nutrition_info,menu_card_image
0,chick_fil_a_chick_n_strips,item_818528ff980240e39250845e28b061f7,Chick-n-Strips,Chick-fil-A,"[American, Fast Food, Southern]","[High Protein, Low Carb, Low Calorie, High Sod...",{},4.29,0.950,"Enjoy tender, hand-breaded Chick-n-Strips, per...",Classic Chicken,"{'contains': ['egg', 'gluten', 'milk', 'wheat'...","{'serving_size': '2 strips', 'calories': 200, ...",https://fastfoodnutrition.org/logos/chick-fil-...
1,chick_fil_a_chicken_nuggets,item_44dbe341c1dd40f095ad04f1bced08e9,Chicken Nuggets,Chick-fil-A,"[American, Fast Food, Southern]","[Low Carb, Low Calorie, High Sodium, Low Sugar]",{},3.49,1.000,"Deliciously crispy, bite-sized chicken nuggets...",Classic Chicken,"{'contains': ['egg', 'gluten', 'milk', 'wheat'...","{'serving_size': '4 nuggets', 'calories': 130,...",https://fastfoodnutrition.org/logos/chick-fil-...
2,chick_fil_a_chicken_nuggets,item_44dbe341c1dd40f095ad04f1bced08e9,Chicken Nuggets,Chick-fil-A,"[American, Fast Food, Southern]","[High Protein, Low Carb, Low Calorie, High Sod...",{},4.99,1.080,"Deliciously crispy, bite-sized chicken nuggets...",Classic Chicken,"{'contains': ['egg', 'gluten', 'milk', 'wheat'...","{'serving_size': '8 nuggets', 'calories': 250,...",https://fastfoodnutrition.org/logos/chick-fil-...
3,chick_fil_a_chicken_nuggets,item_44dbe341c1dd40f095ad04f1bced08e9,Chicken Nuggets,Chick-fil-A,"[American, Fast Food, Southern]","[High Protein, Low Carb, High Calorie, High So...",{},14.99,1.062,"Deliciously crispy, bite-sized chicken nuggets...",Classic Chicken,"{'contains': ['egg', 'gluten', 'milk', 'wheat'...","{'serving_size': '30 nuggets', 'calories': 970...",https://fastfoodnutrition.org/logos/chick-fil-...
4,chick_fil_a_chick_n_strips,item_818528ff980240e39250845e28b061f7,Chick-n-Strips,Chick-fil-A,"[American, Fast Food, Southern]","[High Protein, High Sodium, Low Sugar]",{},6.99,0.951,"Enjoy tender, hand-breaded Chick-n-Strips, per...",Classic Chicken,"{'contains': ['egg', 'gluten', 'milk', 'wheat'...","{'serving_size': '4 strips', 'calories': 410, ...",https://fastfoodnutrition.org/logos/chick-fil-...

In [63]:
# Taco Bell items
df_tb.head()

,item_id,menu_item_id,menu_item_name,restaurant_name,cuisine_type,macronutrient_profile,recipe_items,price,golden_ratio,ai_description,category,allergen_info,nutrition_info,menu_card_image,meal_category
0,taco_bell_bean_burrito,item_bc872feac0cd4c038de6a4bc27b91eef,Bean Burrito,Taco Bell,"[Mexican, American, Fast Food]","[High Carb, Low Calorie, High Sodium, Low Sugar]",{},1.29,0.371,Savor the hearty blend of seasoned refried bea...,Burritos,"{'contains': ['gluten', 'milk', 'wheat'], 'may...","{'serving_size': '1 burrito', 'calories': 350,...",https://fastfoodnutrition.org/logos/taco-bell.jpg,Entree
1,taco_bell_beefy_5_layer_burrito,item_68a8b72cef0e4ac9acf2b3cb8445ef23,Beefy 5-Layer Burrito,Taco Bell,"[Mexican, American, Fast Food]","[High Sodium, Low Sugar]",{},2.99,0.367,"Indulge in a hearty Beefy 5-Layer Burrito, pac...",Burritos,"{'contains': ['gluten', 'milk', 'wheat'], 'may...","{'serving_size': '1 burrito', 'calories': 490,...",https://fastfoodnutrition.org/logos/taco-bell.jpg,Entree
2,taco_bell_burrito_supreme_chicken,item_d8bbc465a2ff443f99500235a73971c9,Burrito Supreme - Chicken,Taco Bell,"[Mexican, American, Fast Food]","[High Sodium, Low Sugar]",{},3.99,0.514,Savor the Burrito Supreme filled with tender c...,Burritos,"{'contains': ['gluten', 'milk', 'wheat'], 'may...","{'serving_size': '1 burrito', 'calories': 370,...",https://fastfoodnutrition.org/logos/taco-bell.jpg,Entree
3,taco_bell_chicken_enchilada_burrito,item_2185ad40296c41209c67ba5496401929,Chicken Enchilada Burrito,Taco Bell,"[Mexican, American, Fast Food]","[High Sodium, Low Sugar]",{},3.99,0.500,Savor the bold flavors of our Chicken Enchilad...,Burritos,"{'contains': ['gluten', 'milk', 'wheat'], 'may...","{'serving_size': '1 burrito', 'calories': 380,...",https://fastfoodnutrition.org/logos/taco-bell.jpg,Entree
4,taco_bell_coffee_with_creamer,item_1aaeafaf9be14badb5ce82fcd2e2aaaa,Coffee with Creamer,Taco Bell,"[Mexican, American, Fast Food]","[Low Carb, Low Calorie, Low Sodium, Low Sugar]",{},2.49,0.667,Savor the smooth blend of rich coffee and crea...,Beverages,"{'contains': [], 'may_contain': [], 'does_not_...","{'serving_size': '1 coffee', 'calories': 30, '...",https://fastfoodnutrition.org/logos/taco-bell.jpg,Drink

In [ ]:
# chipotle items
df_chipotle.head()

,item_id,menu_item_id,menu_item_name,restaurant_name,cuisine_type,macronutrient_profile,recipe_items,price,golden_ratio,ai_description,category,allergen_info,nutrition_info,menu_card_image
0,chipotle_izze_sparkling_blackberry_soda,item_09007bf4a7904846a73f8438b299f460,Izze Sparkling Blackberry Soda,Chipotle,"[Mexican, Latin American, Tex-Mex]","[High Carb, Low Calorie, Low Sodium, Low Sugar]",{},2.50,0.000,Delight in the effervescent zing of Izze Spark...,Beverages,"{'contains': [], 'may_contain': [], 'does_not_...","{'serving_size': '1 bottle', 'calories': 170, ...",https://fastfoodnutrition.org/logos/chipotle.jpg
1,chipotle_tractor_hibiscus_lemonade,item_86b8d873b6f840e4822df75ba6baac51,Tractor Hibiscus Lemonade,Chipotle,"[Mexican, Latin American, Tex-Mex]","[High Carb, Low Calorie, Low Sodium, Low Sugar]",{},3.50,0.000,Quench your thirst with this refreshing hibisc...,Beverages,"{'contains': [], 'may_contain': [], 'does_not_...","{'serving_size': '22 oz', 'calories': 150, 'ch...",https://fastfoodnutrition.org/logos/chipotle.jpg
2,chipotle_chicken_burrito_bowl,item_66a6aa38b02d47208ed7141199aec1e1,Chicken Burrito Bowl,Chipotle,"[Mexican, Latin American, Tex-Mex]","[High Protein, Low Carb, Low Calorie, Low Sugar]",{},8.50,1.684,"Savor a hearty Chicken Burrito Bowl, featuring...",Burrito Bowls,"{'contains': [], 'may_contain': [], 'does_not_...","{'serving_size': '4 oz', 'calories': 190, 'cho...",https://fastfoodnutrition.org/logos/chipotle.jpg
3,chipotle_black_beans,item_1c084543ac7b4259873ac1bf141574e9,Black Beans,Chipotle,"[Mexican, Latin American, Tex-Mex]","[High Carb, Low Calorie, Low Sugar]",{},2.50,0.583,"Savor our hearty black beans, perfectly season...",Extras and Toppings,"{'contains': [], 'may_contain': [], 'does_not_...","{'serving_size': '4 oz', 'calories': 120, 'cho...",https://fastfoodnutrition.org/logos/chipotle.jpg
4,chipotle_carnitas_burrito,item_7d30d25697de4ecdaab8169d37d5e74a,Carnitas Burrito,Chipotle,"[Mexican, Latin American, Tex-Mex]","[High Protein, High Sodium, Low Sugar, Balanced]",{},9.75,0.708,"Savor the tender, slow-cooked carnitas wrapped...",Burritos,"{'contains': ['gluten', 'sulfites', 'wheat'], ...","{'serving_size': '4 oz', 'calories': 480, 'cho...",https://fastfoodnutrition.org/logos/chipotle.jpg

### Categories

Display all categories for Chick-fil-A, Taco Bell, and Chipotle.

In [5]:
cfa_categories = df_cfa['category'].unique()
tb_categories = df_tb['category'].unique()
chip_categories = df_chipotle['category'].unique()

print(f"Chick fil A categories: {cfa_categories}")
print(f"Taco Bell categories: {tb_categories}")
print(f"Chipotle categories: {chip_categories}")

Chick fil A categories: ['Classic Chicken' 'Beverages' 'Breakfast' 'Desserts' "Kid's Meal"
 'Salad Dressings' 'Cool Wraps' 'Sauces' 'Sides' 'Salads']
Taco Bell categories: ['Burritos' 'Beverages' 'Tacos' 'Breakfast' 'Cantina Chicken'
 'Condiments & Sauces' 'Chalupas' 'Nachos' 'Sides' 'Specialties']
Chipotle categories: ['Beverages' 'Burrito Bowls' 'Extras and Toppings' 'Burritos'
 'Quesadillas' 'Salads' 'Tacos' 'Lifestyle Bowls' 'Tortilla Chips']

## Exploring Data

Checking the content of some categories to distinguish what meal component they may be. (Feel free to explore yourself)

### Chick-fil-A Data

In [ ]:
'''Chick fil A categories: ['Classic Chicken' 'Beverages' 'Breakfast' 'Desserts' "Kid's Meal"
 'Salad Dressings' 'Cool Wraps' 'Sauces' 'Sides' 'Salads']'''

cfa_cat_name = "Breakfast"
display(df_cfa.loc[df_cfa['category'] == cfa_cat_name])

,item_id,menu_item_id,menu_item_name,restaurant_name,cuisine_type,macronutrient_profile,recipe_items,price,golden_ratio,ai_description,category,allergen_info,nutrition_info,menu_card_image
53,chick_fil_a_hash_brown_scramble_burrito,item_57b571666c3e48fc8f253bb0e65e1315,Hash Brown Scramble Burrito,Chick-fil-A,"[American, Fast Food, Southern]","[High Protein, High Fat, High Calorie, High So...",{},4.99,0.486,Savor a hearty breakfast with our Hash Brown S...,Breakfast,"{'contains': ['egg', 'gluten', 'milk', 'soy', ...","{'serving_size': '1 burrito', 'calories': 700,...",https://fastfoodnutrition.org/logos/chick-fil-...
55,chick_fil_a_bacon_egg_cheese_biscuit,item_4113c01c405f4ec5ac415e8ffa67c34d,"Bacon, Egg & Cheese Biscuit",Chick-fil-A,"[American, Fast Food, Southern]","[High Sodium, Low Sugar]",{},3.99,0.357,"Start your day right with a flaky, buttery bis...",Breakfast,"{'contains': ['egg', 'gluten', 'milk', 'soy', ...","{'serving_size': '1 biscuit', 'calories': 420,...",https://fastfoodnutrition.org/logos/chick-fil-...
57,chick_fil_a_chicken_biscuit,item_8c359b035e514162add9db3dfcca12c7,Chicken Biscuit,Chick-fil-A,"[American, Fast Food, Southern]","[High Sodium, Low Sugar]",{},3.99,0.413,Start your day with a flaky buttermilk biscuit...,Breakfast,"{'contains': ['egg', 'gluten', 'milk', 'soy', ...","{'serving_size': '1 biscuit', 'calories': 460,...",https://fastfoodnutrition.org/logos/chick-fil-...
58,chick_fil_a_yogurt_parfait_w_cookie_cumbs,item_696737d778b34b2caf288baebc324099,Yogurt Parfait w/ Cookie Cumbs,Chick-fil-A,"[American, Fast Food, Southern]","[Low Calorie, Low Sodium, Low Sugar]",{},4.99,0.480,Indulge in a creamy yogurt parfait layered wit...,Breakfast,"{'contains': ['gluten', 'milk', 'soy', 'wheat'...","{'serving_size': '1 parfait', 'calories': 250,...",https://fastfoodnutrition.org/logos/chick-fil-...
60,chick_fil_a_egg_cheese_english_muffin,item_07042d87afd04700973507580773663d,Egg & Cheese English Muffin,Chick-fil-A,"[American, Fast Food, Southern]","[Low Calorie, High Sodium, Low Sugar]",{},3.99,0.533,Start your day with a fluffy egg and melted ch...,Breakfast,"{'contains': ['egg', 'gluten', 'milk', 'soy', ...","{'serving_size': '1 sandwich', 'calories': 300...",https://fastfoodnutrition.org/logos/chick-fil-...
61,chick_fil_a_hash_brown_scramble_burrito,item_57b571666c3e48fc8f253bb0e65e1315,Hash Brown Scramble Burrito,Chick-fil-A,"[American, Fast Food, Southern]","[High Protein, High Fat, High Calorie, High So...",{},4.99,0.394,Savor a hearty breakfast with our Hash Brown S...,Breakfast,"{'contains': ['egg', 'gluten', 'milk', 'soy', ...","{'serving_size': '1 burrito', 'calories': 710,...",https://fastfoodnutrition.org/logos/chick-fil-...
62,chick_fil_a_yogurt_parfait_with_harvest_nut_gr...,item_440d8ca23c2b4ecfa16ddc71e9c0d1aa,Yogurt Parfait with Harvest Nut Granola,Chick-fil-A,"[American, Fast Food, Southern]","[Low Calorie, Low Sodium, Low Sugar]",{},4.99,0.464,Start your day with a delightful blend of crea...,Breakfast,"{'contains': ['milk', 'tree nuts'], 'may_conta...","{'serving_size': '1 parfait', 'calories': 280,...",https://fastfoodnutrition.org/logos/chick-fil-...
65,chick_fil_a_egg_white_grill,item_403c6de25b2845a0b3804449be646e8a,Egg White Grill,Chick-fil-A,"[American, Fast Food, Southern]","[High Protein, Low Calorie, High Sodium, Low S...",{},4.99,0.862,"Start your day with our Egg White Grill, featu...",Breakfast,"{'contains': ['egg', 'gluten', 'milk', 'soy', ...","{'serving_size': '1 sandwich', 'calories': 290...",https://fastfoodnutrition.org/logos/chick-fil-...
66,chick_fil_a_hash_brown_scramble_bowl,item_cd3d9826a6cd40e58b2bd0eaf8a084df,Hash Brown Scramble Bowl,Chick-fil-A,"[American, Fast Food, Southern]","[High Protein, Low Carb, High Fat, High Sodium...",{},6.99,0.617,"Savor the hearty Hash Brown Scramble Bowl, fea...",Breakfast,"{'contains': ['egg', 'milk', 'soy'], 'may_cont...","{'serving_size': '1 bowl', 'calories': 470, 'c...",https://fastfoodnutrition.org/logos/chick-fil-...
67,chick_fil_a_chicken_egg_cheese_biscuit,item_be2be90336df444faa0fc92fe6768944,"Chicken, Egg & Cheese Biscuit",Chick-fil-A,"[American, Fast Food, Southern]","[High Protein, High Sodium, Low Sugar]",{},4.99,0.491,Start your day with a flaky biscuit layered wi...,Breakfast,"{'contains': ['egg', 'gluten', 'milk', 'soy', ...","{'serving_size': '206g', 'calories': 530, 'cho...",https://fastfoodnutrition.org/logos/chick-fil-...
68,chick_fil_a_egg_cheese_english_muffin,item_07042d87afd04700973507580773663d,Egg & Cheese English Muffin,Chick-fil-A,"[American, Fast Food, Southern]","[High Fat, High Sodium, Low Sugar]",{},4.99,0.462,Start your day with a fluffy egg and melted ch...,Breakfast,"{'contains': ['egg', 'gluten', 'milk', 'soy', ...","{'serving_size': '1 sandwich', 'calories': 520...",https://fastfoodnutrition.org/logos/chick-fil-...
70,chick_fil_a_hash_brown_scramble_bowl,item_cd3d9826a6cd40e58b2bd0eaf8a084df,Hash Brown Scramble Bowl,Chick-fil-A,"[American, Fast Food, Southern]","[Low Carb, High Fat, High Sodium, Low Sugar]",{},5.99,0.479,"Savor the hearty Hash Brown Scramble Bowl, fea...",Breakfast,"{'contains': ['egg', 'milk', 'soy'], 'may_cont...","{'serving_size': '1 bowl', 'calories': 480, 'c...",https://fastfoodnutrition.org/logos/chick-fil-...
71,chick_fil_a_sausage_egg_and_cheese_biscuit,item_b10274268e6548108b9d1b1058b026e3,Sausage Egg and Cheese Biscuit,Chick-fil-A,"[American, Fast Food, Southern]","[High Fat, High Sodium, Low Sugar]",{},3.99,0.365,Indulge in a flaky buttermilk biscuit layered ...,Breakfast,"{'contains': ['egg', 'gluten', 'milk', 'soy', ...","{'serving_size': '1 biscuit', 'calories': 630,...",https://fastfoodnutrition.org/logos/chick-fil-...
74,chick_fil_a_hot_buttered_biscuit,item_80103285c8bc4f86881e8e077169afe1,Hot Buttered Biscuit,Chick-fil-A,"[American, Fast Food, Southern]","[Low Protein, Low Calorie, High Sodium, Low Su...",{},2.49,0.138,"Indulge in our flaky, warm Hot Buttered Biscui...",Breakfast,"{'contains': ['gluten', 'milk', 'soy', 'wheat'...","{'serving_size': '1 biscuit', 'calories': 290,...",https://fastfoodnutrition.org/logos/chick-fil-...
76,chick_fil_a_chick_n_minis,item_66c20fcaff8644dfa4e339fe9772a52c,Chick-n-Minis,Chick-fil-A,"[American, Fast Food, Southern]","[Low Calorie, High Sodium, Low Sugar]",{},3.99,0.571,"Delight in a warm, fluffy biscuit filled with ...",Breakfast,"{'contains': ['egg', 'gluten', 'milk', 'soy', ...","{'serving_size': '94g', 'calories': 280, 'chol...",https://fastfoodnutrition.org/logos/chick-fil-...
79,chick_fil_a_chick_n_minis,item_66c20fcaff8644dfa4e339fe9772a52c,Chick-n-Minis,Chick-fil-A,"[American, Fast Food, Southern]","[High Protein, High Calorie, High Sodium, Low ...",{},14.99,0.552,"Delight in a warm, fluffy biscuit filled with ...",Breakfast,"{'contains': ['egg', 'gluten', 'milk', 'soy', ...","{'serving_size': '10 sliders', 'calories': 870...",https://fastfoodnutrition.org/logos/chick-fil-...
80,chick_fil_a_hash_brown_scramble_bowl,item_cd3d9826a6cd40e58b2bd0eaf8a084df,Hash Brown Scramble Bowl,Chick-fil-A,"[American, Fast Food, Southern]","[High Protein, Low Carb, High Fat, High Sodium...",{},6.99,0.732,"Savor the hearty Hash Brown Scramble Bowl, fea...",Breakfast,"{'contains': ['egg', 'milk', 'soy'], 'may_cont...","{'serving_size': '1 bowl', 'calories': 410, 'c...",https://fastfoodnutrition.org/logos/chick-fil-...
81,chick_fil_a_hash_brown_scramble_burrito,item_57b571666c3e48fc8f253bb0e65e1315,Hash Brown Scramble Burrito,Chick-fil-A,"[American, Fast Food, Southern]",[],{},4.99,0.000,Savor a hearty breakfast with our Hash Brown S...,Breakfast,"{'contains': ['egg', 'gluten', 'milk', 'soy', ...","{'serving_size': '1 serving', 'calories': 0, '...",https://fastfoodnutrition.org/logos/chick-fil-...
82,chick_fil_a_hash_brown_scramble_burrito,item_57b571666c3e48fc8f253bb0e65e1315,Hash Brown Scramble Burrito,Chick-fil-A,"[American, Fast Food, Southern]","[High Protein, High Sodium, Low Sugar]",{},6.99,0.538,Savor a hearty breakfast with our Hash Brown S...,Breakfast,"{'contains': ['egg', 'gluten', 'milk', 'soy', ...","{'serving_size': '1 burrito', 'calories': 650,...",https://fastfoodnutrition.org/logos/chick-fil-...
86,chick_fil_a_chick_n_minis,item_66c20fcaff8644dfa4e339fe9772a52c,Chick-n-Minis,Chick-fil-A,"[American, Fast Food, Southern]","[High Sodium, Low Sugar, Balanced]",{},4.29,0.568,"Delight in a warm, fluffy biscuit filled with ...",Breakfast,"{'contains': ['egg', 'gluten', 'milk', 'soy', ...","{'serving_size': '126g', 'calories': 370, 'cho...",https://fastfoodnutrition.org/logos/chick-fil-...
87,chick_fil_a_chicken_egg_cheese_muffin,item_a7c5d7c2c4d34bb1b9d1d6172662fd79,"Chicken, Egg, & Cheese Muffin",Chick-fil-A,"[American, Fast Food, Southern]","[High Protein, High Sodium, Low Sugar]",{},4.99,0.643,"Start your day with a savory Chicken, Egg, & C...",Breakfast,"{'contains': ['egg', 'gluten', 'milk', 'soy', ...","{'serving_size': '190g', 'calories': 420, 'cho...",https://fastfoodnutrition.org/logos/chick-fil-...
88,chick_fil_a_english_muffin,item_563cef2dab0c4a04a3b41560ab98967a,English Muffin,Chick-fil-A,"[American, Fast Food, Southern]","[High Carb, Low Calorie, Low Sodium, Low Sugar]",{},2.49,0.357,"Start your day right with a warm, toasted Engl...",Breakfast,"{'contains': ['gluten', 'wheat'], 'may_contain...","{'serving_size': '1 English muffin', 'calories...",https://fastfoodnutrition.org/logos/chick-fil-...
89,chick_fil_a_hash_brown_scramble_bowl,item_cd3d9826a6cd40e58b2bd0eaf8a084df,Hash Brown Scramble Bowl,Chick-fil-A,"[American, Fast Food, Southern]","[High Protein, Low Carb, High Fat, High Sodium...",{},6.99,0.609,"Savor the hearty Hash Brown Scramble Bowl, fea...",Breakfast,"{'contains': ['egg', 'milk', 'soy'], 'may_cont...","{'serving_size': '1 bowl', 'calories': 460, 'c...",https://fastfoodnutrition.org/logos/chick-fil-...
90,chick_fil_a_hash_browns,item_0589871236764832a5e65428d0048eac,Hash Browns,Chick-fil-A,"[American, Fast Food, Southern]","[Low Protein, High Fat, Low Calorie, Low Sugar]",{},2.99,0.111,"Delightfully crispy and golden, our Hash Brown...",Breakfast,"{'contains': [], 'may_contain': [], 'does_not_...","{'serving_size': '77g', 'calories': 270, 'chol...",https://fastfoodnutrition.org/logos/chick-fil-...
92,chick_fil_a_spicy_chicken_biscuit,item_b0056ed759974de0ae0ef93c4bc18032,Spicy Chicken Biscuit,Chick-fil-A,"[American, Fast Food, Southern]","[High Sodium, Low Sugar]",{},4.99,0.395,"Start your day with a spicy, crispy chicken fi...",Breakfast,"{'contains': ['egg', 'gluten', 'milk', 'soy', ...","{'serving_size': '145g', 'calories': 430, 'cho...",https://fastfoodnutrition.org/logos/chick-fil-...

### Taco Bell Data

In [33]:
'''Taco Bell categories: ['Burritos' 'Beverages' 'Tacos' 'Breakfast' 'Cantina Chicken'
 'Condiments & Sauces' 'Chalupas' 'Nachos' 'Sides' 'Specialties']'''

tb_cat_name = "Condiments & Sauces"
display(df_tb.loc[df_tb['category'] == tb_cat_name])

,item_id,menu_item_id,menu_item_name,restaurant_name,cuisine_type,macronutrient_profile,recipe_items,price,golden_ratio,ai_description,category,allergen_info,nutrition_info,menu_card_image,meal_category
129,taco_bell_mild_sauce,item_b1a34e10fe684507b6e87b1a29dc95e6,Mild Sauce,Taco Bell,"[Mexican, American, Fast Food]",[],{},1.00,0.000,Add a zesty kick to your meal with Taco Bell's...,Condiments & Sauces,"{'contains': ['soy'], 'may_contain': [], 'does...","{'serving_size': '1 packet', 'calories': 0, 'c...",https://fastfoodnutrition.org/logos/taco-bell.jpg,Add-On
131,taco_bell_breakfast_salsa,item_ee95089c94294d589ac6839024ae4ecb,Breakfast Salsa,Taco Bell,"[Mexican, American, Fast Food]","[Low Carb, Low Calorie, Low Sodium, Low Sugar]",{},1.00,0.000,Elevate your breakfast with Taco Bell's zesty ...,Condiments & Sauces,"{'contains': ['gluten', 'soy', 'wheat'], 'may_...","{'serving_size': '1 packet', 'calories': 0, 'c...",https://fastfoodnutrition.org/logos/taco-bell.jpg,Add-On
132,taco_bell_nugget_dipping_sauce,item_2ebeb298d6cc4d98b88fc6ad8a9db7dc,Nugget Dipping Sauce,Taco Bell,"[Mexican, American, Fast Food]","[Low Carb, High Fat, Low Calorie, Low Sodium, ...",{},1.00,0.000,"Delightfully creamy and savory, this rich nugg...",Condiments & Sauces,"{'contains': ['egg', 'gluten', 'milk', 'soy', ...","{'serving_size': '1.5 oz', 'calories': 200, 'c...",https://fastfoodnutrition.org/logos/taco-bell.jpg,Add-On
133,taco_bell_pepper_jack_sauce,item_b076a600c6584b8f9234c6f9a40d9780,Pepper Jack Sauce,Taco Bell,"[Mexican, American, Fast Food]","[Low Carb, High Fat, Low Calorie, Low Sodium, ...",{},1.00,0.000,Spice up your meal with our zesty Pepper Jack ...,Condiments & Sauces,"{'contains': [], 'may_contain': [], 'does_not_...","{'serving_size': '14g', 'calories': 70, 'chole...",https://fastfoodnutrition.org/logos/taco-bell.jpg,Add-On
134,taco_bell_premium_guacamole_dip,item_57756f900d064b1c8acc474e942926d8,Premium Guacamole Dip,Taco Bell,"[Mexican, American, Fast Food]","[Low Carb, High Fat, Low Calorie, Low Sodium, ...",{},1.49,0.143,"Savor the creamy, fresh taste of our Premium G...",Condiments & Sauces,"{'contains': [], 'may_contain': [], 'does_not_...","{'serving_size': '43g', 'calories': 70, 'chole...",https://fastfoodnutrition.org/logos/taco-bell.jpg,Add-On
136,taco_bell_creamy_jalapeno_sauce,item_21f4680809bf4371bb5548cc92c355ad,Creamy Jalapeno Sauce,Taco Bell,"[Mexican, American, Fast Food]","[Low Carb, High Fat, Low Calorie, Low Sodium, ...",{},1.00,0.000,Elevate your meal with our luscious creamy jal...,Condiments & Sauces,"{'contains': [], 'may_contain': [], 'does_not_...","{'serving_size': '14g', 'calories': 70, 'chole...",https://fastfoodnutrition.org/logos/taco-bell.jpg,Add-On
137,taco_bell_red_sauce,item_25816abada984710ad3583e845c86afb,Red Sauce,Taco Bell,"[Mexican, American, Fast Food]","[Low Carb, Low Calorie, Low Sodium, Low Sugar]",{},1.00,0.000,Elevate your meal with Taco Bell's zesty Red S...,Condiments & Sauces,"{'contains': [], 'may_contain': [], 'does_not_...","{'serving_size': '28g', 'calories': 10, 'chole...",https://fastfoodnutrition.org/logos/taco-bell.jpg,Add-On
138,taco_bell_reduced_fat_sour_cream_dip,item_550942d163114ef9b28c00a7059833cf,Reduced-Fat Sour Cream Dip,Taco Bell,"[Mexican, American, Fast Food]","[Low Carb, High Fat, Low Calorie, Low Sodium, ...",{},1.49,0.167,Indulge guilt-free in our Reduced-Fat Sour Cre...,Condiments & Sauces,"{'contains': [], 'may_contain': [], 'does_not_...","{'serving_size': '43g', 'calories': 60, 'chole...",https://fastfoodnutrition.org/logos/taco-bell.jpg,Add-On
139,taco_bell_salsa,item_de49ee06b6754e869f52d8121a22a6c8,Salsa,Taco Bell,"[Mexican, American, Fast Food]","[Low Carb, Low Calorie, Low Sodium, Low Sugar]",{},1.00,0.000,"Zesty and vibrant, our fresh salsa bursts with...",Condiments & Sauces,"{'contains': [], 'may_contain': [], 'does_not_...","{'serving_size': '21g', 'calories': 5, 'choles...",https://fastfoodnutrition.org/logos/taco-bell.jpg,Add-On
142,taco_bell_hot_sauce,item_d485a1a5657a47d9b7d8b9be477d9a0b,Hot Sauce,Taco Bell,"[Mexican, American, Fast Food]",[],{},1.00,0.000,Elevate your meal with Taco Bell's zesty Hot S...,Condiments & Sauces,"{'contains': [], 'may_contain': [], 'does_not_...","{'serving_size': '1 packet', 'calories': 0, 'c...",https://fastfoodnutrition.org/logos/taco-bell.jpg,Add-On
143,taco_bell_nugget_dipping_sauce,item_2ebeb298d6cc4d98b88fc6ad8a9db7dc,Nugget Dipping Sauce,Taco Bell,"[Mexican, American, Fast Food]","[Low Carb, High Fat, Low Calorie, Low Sodium, ...",{},1.00,0.000,"Delightfully creamy and savory, this rich nugg...",Condiments & Sauces,"{'contains': ['egg', 'gluten', 'milk', 'soy', ...","{'serving_size': '1.5 oz', 'calories': 210, 'c...",https://fastfoodnutrition.org/logos/taco-bell.jpg,Add-On
145,taco_bell_diablo_sauce,item_89e18e63e25242a78c7bbb6a8670e02f,Diablo Sauce,Taco Bell,"[Mexican, American, Fast Food]",[],{},1.00,0.000,"Experience the fiery kick of Diablo Sauce, a b...",Condiments & Sauces,"{'contains': ['gluten'], 'may_contain': [], 'd...","{'serving_size': '1 packet', 'calories': 0, 'c...",https://fastfoodnutrition.org/logos/taco-bell.jpg,Add-On
146,taco_bell_salsa_verde,item_b53e9d3fe55d416d84f42e910db685ce,Salsa Verde,Taco Bell,"[Mexican, American, Fast Food]","[Low Carb, Low Calorie, Low Sodium, Low Sugar]",{},1.00,0.000,Bright and zesty Salsa Verde bursts with fresh...,Condiments & Sauces,"{'contains': [], 'may_contain': [], 'does_not_...","{'serving_size': '6g', 'calories': 5, 'cholest...",https://fastfoodnutrition.org/logos/taco-bell.jpg,Add-On
149,taco_bell_cilantro_dressing,item_f65327221b254042b242e76fd96045e4,Cilantro Dressing,Taco Bell,"[Mexican, American, Fast Food]","[Low Carb, High Fat, Low Calorie, Low Sodium, ...",{},1.00,0.000,Zesty cilantro dressing brings a burst of vibr...,Condiments & Sauces,"{'contains': [], 'may_contain': [], 'does_not_...","{'serving_size': '28g', 'calories': 90, 'chole...",https://fastfoodnutrition.org/logos/taco-bell.jpg,Add-On
150,taco_bell_green_tomatillo_sauce,item_5a84f49c2b2048009b73e4875fc13443,Green Tomatillo Sauce,Taco Bell,"[Mexican, American, Fast Food]","[Low Carb, Low Calorie, Low Sodium, Low Sugar]",{},1.00,0.000,Zesty green tomatillo sauce bursts with vibran...,Condiments & Sauces,"{'contains': [], 'may_contain': [], 'does_not_...","{'serving_size': '28g', 'calories': 10, 'chole...",https://fastfoodnutrition.org/logos/taco-bell.jpg,Add-On
151,taco_bell_guacamole,item_3673039a1d96483fa6bafd1219f8a2a5,Guacamole,Taco Bell,"[Mexican, American, Fast Food]","[Low Carb, High Fat, Low Calorie, Low Sodium, ...",{},1.49,0.000,"Smooth, creamy guacamole made from ripe avocad...",Condiments & Sauces,"{'contains': [], 'may_contain': [], 'does_not_...","{'serving_size': '21g', 'calories': 35, 'chole...",https://fastfoodnutrition.org/logos/taco-bell.jpg,Add-On
152,taco_bell_nugget_dipping_sauce,item_2ebeb298d6cc4d98b88fc6ad8a9db7dc,Nugget Dipping Sauce,Taco Bell,"[Mexican, American, Fast Food]","[Low Carb, High Fat, Low Calorie, Low Sodium, ...",{},1.00,0.000,"Delightfully creamy and savory, this rich nugg...",Condiments & Sauces,"{'contains': ['egg', 'gluten', 'milk', 'soy', ...","{'serving_size': '1.5 oz', 'calories': 210, 'c...",https://fastfoodnutrition.org/logos/taco-bell.jpg,Add-On
156,taco_bell_pico_de_gallo,item_224b6c9b78004f0195c008c797cd9ae9,Pico de Gallo,Taco Bell,"[Mexican, American, Fast Food]","[Low Carb, Low Calorie, Low Sodium, Low Sugar]",{},1.29,0.000,"Zesty pico de gallo featuring diced tomatoes, ...",Condiments & Sauces,"{'contains': [], 'may_contain': [], 'does_not_...","{'serving_size': '21g', 'calories': 5, 'choles...",https://fastfoodnutrition.org/logos/taco-bell.jpg,Add-On
157,taco_bell_salsa_dip,item_845c7684c2ab4c758dad9635386cb1f3,Salsa Dip,Taco Bell,"[Mexican, American, Fast Food]","[Low Carb, Low Calorie, Low Sodium, Low Sugar]",{},1.49,0.000,"Zesty and vibrant, our Salsa Dip blends ripe t...",Condiments & Sauces,"{'contains': [], 'may_contain': [], 'does_not_...","{'serving_size': '43g', 'calories': 10, 'chole...",https://fastfoodnutrition.org/logos/taco-bell.jpg,Add-On
158,taco_bell_reduced_fat_sour_cream,item_10f9e73cfcab46b0b6a6a8c349dafbce,Reduced Fat Sour Cream,Taco Bell,"[Mexican, American, Fast Food]","[Low Carb, High Fat, Low Calorie, Low Sodium, ...",{},1.00,0.333,Creamy and tangy reduced fat sour cream adds a...,Condiments & Sauces,"{'contains': [], 'may_contain': [], 'does_not_...","{'serving_size': '21g', 'calories': 30, 'chole...",https://fastfoodnutrition.org/logos/taco-bell.jpg,Add-On
161,taco_bell_fire_sauce,item_f0d2b6bd85e644c180f213f736f88dab,Fire Sauce,Taco Bell,"[Mexican, American, Fast Food]",[],{},1.00,0.000,"Add a fiery kick to your meal with this bold, ...",Condiments & Sauces,"{'contains': ['gluten', 'soy', 'wheat'], 'may_...","{'serving_size': '1 packet', 'calories': 0, 'c...",https://fastfoodnutrition.org/logos/taco-bell.jpg,Add-On
167,taco_bell_spicy_ranch_dip,item_7e8438a5632c4accaf0a34184bf3de7b,Spicy Ranch Dip,Taco Bell,"[Mexican, American, Fast Food]","[Low Carb, High Fat, Low Calorie, Low Sugar, K...",{},1.49,0.043,"Indulge in this creamy, zesty dip infused with...",Condiments & Sauces,"{'contains': [], 'may_contain': [], 'does_not_...","{'serving_size': '43g', 'calories': 230, 'chol...",https://fastfoodnutrition.org/logos/taco-bell.jpg,Add-On
168,taco_bell_nacho_cheese_dip,item_90e6b83a5351467a89d238d4761ac5a2,Nacho Cheese Dip,Taco Bell,"[Mexican, American, Fast Food]","[Low Carb, High Fat, Low Calorie, Low Sugar, K...",{},1.49,0.600,"Indulge in our creamy Nacho Cheese Dip, a velv...",Condiments & Sauces,"{'contains': [], 'may_contain': [], 'does_not_...","{'serving_size': '40g', 'calories': 150, 'chol...",https://fastfoodnutrition.org/logos/taco-bell.jpg,Add-On
169,taco_bell_pizza_sauce,item_173cbf2ddce147b180cfea34697b6cb1,Pizza Sauce,Taco Bell,"[Mexican, American, Fast Food]","[Low Carb, Low Calorie, Low Sodium, Low Sugar]",{},1.00,0.000,"Zesty and vibrant, our pizza sauce delivers a ...",Condiments & Sauces,"{'contains': [], 'may_contain': [], 'does_not_...","{'serving_size': '28g', 'calories': 10, 'chole...",https://fastfoodnutrition.org/logos/taco-bell.jpg,Add-On

### Chipotle Data

In [106]:
'''Chipotle categories: ['Beverages' 'Burrito Bowls' 'Extras and Toppings' 'Burritos'
 'Quesadillas' 'Salads' 'Tacos' 'Lifestyle Bowls' 'Tortilla Chips']'''

chip_cat_name = "Burrito Bowls"
display(df_chipotle.loc[df_chipotle['category'] == chip_cat_name])

,item_id,menu_item_id,menu_item_name,restaurant_name,cuisine_type,macronutrient_profile,recipe_items,price,golden_ratio,ai_description,category,allergen_info,nutrition_info,menu_card_image
2,chipotle_chicken_burrito_bowl,item_66a6aa38b02d47208ed7141199aec1e1,Chicken Burrito Bowl,Chipotle,"[Mexican, Latin American, Tex-Mex]","[High Protein, Low Carb, Low Calorie, Low Sugar]",{},8.50,1.684,"Savor a hearty Chicken Burrito Bowl, featuring...",Burrito Bowls,"{'contains': [], 'may_contain': [], 'does_not_...","{'serving_size': '4 oz', 'calories': 190, 'cho...",https://fastfoodnutrition.org/logos/chipotle.jpg
13,chipotle_carnitas_burrito_bowl,item_fd10bd13d53e4e8bac079cce1f0e5241,Carnitas Burrito Bowl,Chipotle,"[Mexican, Latin American, Tex-Mex]","[High Protein, Low Carb, Low Calorie, High Sod...",{},8.75,1.421,"Savor the tender, slow-cooked carnitas nestled...",Burrito Bowls,"{'contains': [], 'may_contain': [], 'does_not_...","{'serving_size': '4 oz', 'calories': 190, 'cho...",https://fastfoodnutrition.org/logos/chipotle.jpg
16,chipotle_sofritas_burrito_bowl,item_fd57cee6af6a41398259e3fdc845250f,Sofritas Burrito Bowl,Chipotle,"[Mexican, Latin American, Tex-Mex]","[Low Carb, High Fat, Low Calorie, High Sodium,...",{},7.50,0.552,Savor the robust flavor of our Sofritas Burrit...,Burrito Bowls,"{'contains': ['soy', 'sulfites'], 'may_contain...","{'serving_size': '4 oz', 'calories': 145, 'cho...",https://fastfoodnutrition.org/logos/chipotle.jpg
26,chipotle_plant_based_chorizo_burrito_bowl,item_fd40403bbb2249ee9778ca1b23418fea,Plant Based Chorizo Burrito Bowl,Chipotle,"[Mexican, Latin American, Tex-Mex]","[Low Carb, Low Calorie, High Sodium, Low Sugar]",{},10.50,0.727,Savor the bold flavors of our Plant Based Chor...,Burrito Bowls,"{'contains': [], 'may_contain': [], 'does_not_...","{'serving_size': '1 bowl', 'calories': 220, 'c...",https://fastfoodnutrition.org/logos/chipotle.jpg
30,chipotle_barbacoa_burrito_bowl,item_e74b9bbd0a054a80bf7b3a4d09d01213,Barbacoa Burrito Bowl,Chipotle,"[Mexican, Latin American, Tex-Mex]","[High Protein, Low Carb, Low Calorie, High Sod...",{},9.50,1.412,"Savor the tender, shredded barbacoa beef in a ...",Burrito Bowls,"{'contains': [], 'may_contain': [], 'does_not_...","{'serving_size': '4 oz', 'calories': 170, 'cho...",https://fastfoodnutrition.org/logos/chipotle.jpg
34,chipotle_carne_asada_burrito_bowl,item_648ecf06e0a5471ea24f7ed7a08b0c40,Carne Asada Burrito Bowl,Chipotle,"[Mexican, Latin American, Tex-Mex]","[High Protein, Low Carb, High Fat, Low Calorie...",{},10.50,1.160,Savor the bold flavors of marinated carne asad...,Burrito Bowls,"{'contains': [], 'may_contain': [], 'does_not_...","{'serving_size': '1 bowl', 'calories': 250, 'c...",https://fastfoodnutrition.org/logos/chipotle.jpg
38,chipotle_steak_burrito_bowl,item_68f66e0f17e44a94948d5a826296a40d,Steak Burrito Bowl,Chipotle,"[Mexican, Latin American, Tex-Mex]","[High Protein, Low Carb, Low Calorie, Low Sugar]",{},8.50,1.579,"Savor the bold flavors of tender, marinated st...",Burrito Bowls,"{'contains': [], 'may_contain': [], 'does_not_...","{'serving_size': '4 oz', 'calories': 190, 'cho...",https://fastfoodnutrition.org/logos/chipotle.jpg

In [109]:
# looking at nutrition info for each item to get a better feel for what is in it
# e.g. Chicken Burrito Bowl
print(df_chipotle.loc[2, 'ai_description'])
print(df_chipotle.loc[2, 'nutrition_info'])
print(df_chipotle.loc[2, 'recipe_items'])

# e.g. Carnitas Burrito Bowl
print(df_chipotle.loc[13, 'ai_description'])
print(df_chipotle.loc[13, 'nutrition_info'])
print(df_chipotle.loc[13, 'recipe_items'])

# e.g. Chicken Quesadilla
print(df_chipotle.loc[43, 'nutrition_info'])
print(df_chipotle.loc[43, 'recipe_items'])

Savor a hearty Chicken Burrito Bowl, featuring tender grilled chicken, zesty cilantro-lime rice, fresh salsas, and protein-packed black beans for a satisfying meal.
{'serving_size': '4 oz', 'calories': 190, 'cholesterol': 115, 'sodium': 370, 'total_carbohydrates': 1, 'dietary_fiber': 0, 'sugars': 1, 'protein': 32, 'potassium': 0, 'total_fat': 7}
{}
Savor the tender, slow-cooked carnitas nestled atop a vibrant bed of cilantro-lime rice, black beans, and zesty toppings for a protein-packed delight.
{'serving_size': '4 oz', 'calories': 190, 'cholesterol': 70, 'sodium': 540, 'total_carbohydrates': 1, 'dietary_fiber': 0, 'sugars': 0, 'protein': 27, 'potassium': 0, 'total_fat': 8}
{}
{'serving_size': '1 quesadilla', 'calories': 830, 'cholesterol': 0, 'sodium': 1480, 'total_carbohydrates': 53, 'dietary_fiber': 3, 'sugars': 0, 'protein': 58, 'potassium': 0, 'total_fat': 40}
{}

Breaking down contents of items in Chipotle:
- Looking at the calorie count for a "Burrito Bowl" and referencing the online Chipotle menu, each item appears to only account for the protein itself. The item does not contain any rice, beans, or other add-ons yet.
- Similarly, "Burritos" are most likely just the protein + tortilla. I assume other categories follow a similar pattern.
- "Lifestyle Bowls" are pre-made and complete bowls.
- sidenote: all "Tacos" have a serving size of 3.

### Some Thoughts After Exploring Data

Issue 1: broader categories like "Kid's Meal" and "Breakfast" in Chick fil A contain items that may be from different categories.
- I'm just going to hard code the differences for this example
    - most items in "Breakfast" category can probably be an "Entree" (with the exception of hash browns)
    - items in the "Kid's Meal" are an entree if they have the word "meal" in the name, "milk" for beverage, and the rest would be sides

Issue 2: when computing combinations in the future, should we try to account for 'realistic' combinations?
- If you order a salad, you would probably want salad dressing to go with it. Blindly assigning meals + sides/add-ons won't always be 'realistic'
- Most likely, you wouldn't want to have salad dressing as an add-on when you ordered a chicken sandwich.

Issue 3: "Build-your-own" restaurants (Chipotle) don't exactly map to the 5 categories
- Possible idea: rather than starting off as an "Entree", each item could instead be labeled as a "Base." A "Base" might require that certain conditions are met before it becomes an "Entree." However, this might be hard to generalize:
    - For example, a Burrito Bowl isn't a bowl yet if it contains only protein.
    - A Burrito is basically still a Taco (tortilla + protein) until you add more toppings.
    - However, a user could possibly be satisfied with a Taco being purely tortilla + protein.

## Assign Meal Categories (Entree, Side, Drink, Dessert, Add-on)
Note: this is hard-coded just to have categories to work with.

### Chick-fil-A

In [ ]:
# add a column for meal categories
df_cfa['meal_category'] = 'temp'

# assign meal categories
# note: hard-coded assignment

cfa_entree_categories = ['Classic Chicken', 'Breakfast', 'Cool Wraps', 'Salads', ]
df_cfa.loc[df_cfa['category'].isin(cfa_entree_categories), 'meal_category'] = 'Entree'

df_cfa.loc[df_cfa['category'] == 'Sides', 'meal_category'] = 'Side'

df_cfa.loc[df_cfa['category'] == 'Beverages', 'meal_category'] = 'Drink'

df_cfa.loc[df_cfa['category'] == 'Desserts', 'meal_category'] = 'Dessert'

addon_categories = ['Salad Dressings', 'Sauces']
df_cfa.loc[df_cfa['category'].isin(addon_categories), 'meal_category'] = 'Add-on'

# assigning some categories manually
df_cfa.loc[90, 'meal_category'] = 'Side' # hash brown

kid_mask = df_cfa['category'] == "Kid's Meal"
df_cfa.loc[kid_mask & df_cfa['menu_item_name'].str.contains('Meal', case=False, na=False),'meal_category'] = 'Entree'
df_cfa.loc[kid_mask & df_cfa['menu_item_name'].str.contains('Milk', case=False, na=False),'meal_category'] = 'Drink'
df_cfa.loc[kid_mask & ~df_cfa['menu_item_name'].str.contains('Meal|Milk', case=False, na=False),'meal_category'] = 'Side'

In [16]:
# check that all items got assigned a category
display(df_cfa.loc[df_cfa['meal_category'] == 'temp'])

Empty DataFrame
Columns: [item_id, menu_item_id, menu_item_name, restaurant_name, cuisine_type, macronutrient_profile, recipe_items, price, golden_ratio, ai_description, category, allergen_info, nutrition_info, menu_card_image, meal_category]
Index: []

Sorting the menu items for CFA by category:

In [82]:
# placeholder: storing menu items just by their ID

cfa_entrees = list(df_cfa.loc[df_cfa['meal_category'] == 'Entree', 'menu_item_id'])
cfa_sides = list(df_cfa.loc[df_cfa['meal_category'] == 'Side', 'menu_item_id'])
cfa_drinks = list(df_cfa.loc[df_cfa['meal_category'] == 'Drink', 'menu_item_id'])
cfa_desserts = list(df_cfa.loc[df_cfa['meal_category'] == 'Dessert', 'menu_item_id'])
cfa_addons = list(df_cfa.loc[df_cfa['meal_category'] == 'Add-on', 'menu_item_id'])

print(f"Count of Entrees: {len(cfa_entrees)}")
print(f"Count of Sides: {len(cfa_sides)}")
print(f"Count of Drinks: {len(cfa_drinks)}")
print(f"Count of Desserts: {len(cfa_desserts)}")
print(f"Count of Add-Ons: {len(cfa_addons)}")

Count of Entrees: 76
Count of Sides: 19
Count of Drinks: 43
Count of Desserts: 24
Count of Add-Ons: 15

### Taco Bell

Items of concern:
- Cheesy roll up in 'Specialties': not sufficient to be an entree
- Cinnabon Delights (2, 4, and 12 pc): I will put in "Dessert" for now

In [79]:
# add a column for meal categories
df_tb['meal_category'] = 'temp'

tb_entree_categories = ['Burritos', 'Tacos', 'Breakfast', 'Cantina Chicken','Chalupas', 'Nachos', 'Specialties']
df_tb.loc[df_tb['category'].isin(tb_entree_categories), 'meal_category'] = 'Entree'

df_tb.loc[df_tb['category'] == 'Sides', 'meal_category'] = 'Side'

df_tb.loc[df_tb['category'] == 'Beverages', 'meal_category'] = 'Drink'

df_tb.loc[df_tb['category'] == "Condiments & Sauces", 'meal_category'] = 'Add-on'

# manual assignments
df_tb.loc[91, 'meal_category'] = 'Side'     # hash brown
df_tb.loc[194, 'meal_category'] = 'Side'    # cheesy roll up
df_tb.loc[df_tb['menu_item_name'] == "Cinnabon Delights", 'meal_category'] = 'Dessert'

In [77]:
# check that all items got assigned a category
display(df_tb.loc[df_tb['meal_category'] == 'temp'])

Empty DataFrame
Columns: [item_id, menu_item_id, menu_item_name, restaurant_name, cuisine_type, macronutrient_profile, recipe_items, price, golden_ratio, ai_description, category, allergen_info, nutrition_info, menu_card_image, meal_category]
Index: []

Sorting the menu items for Taco Bell by category:

In [80]:
tb_entrees = list(df_tb.loc[df_tb['meal_category'] == 'Entree', 'menu_item_id'])
tb_sides = list(df_tb.loc[df_tb['meal_category'] == 'Side', 'menu_item_id'])
tb_drinks = list(df_tb.loc[df_tb['meal_category'] == 'Drink', 'menu_item_id'])
tb_desserts = list(df_tb.loc[df_tb['meal_category'] == 'Dessert', 'menu_item_id'])
tb_addons = list(df_tb.loc[df_tb['meal_category'] == 'Add-on', 'menu_item_id'])

print(f"Count of Entrees: {len(tb_entrees)}")
print(f"Count of Sides: {len(tb_sides)}")
print(f"Count of Drinks: {len(tb_drinks)}")
print(f"Count of Desserts: {len(tb_desserts)}")
print(f"Count of Add-Ons: {len(tb_addons)}")

Count of Entrees: 75
Count of Sides: 16
Count of Drinks: 87
Count of Desserts: 3
Count of Add-Ons: 24

### Chipotle: TBD

## Meal Combination Exploration

Information to calculate when storing meals:
- calories
- protein
- price

### Chick-fil-A

Naive approach: precompute all meals

In [1]:
import itertools

In [ ]:
# forcing the combo to at least have Entree, Side, and Drink
def compute_all_cfa_combos(addons=False, desssert=False):
    categories = [cfa_entrees, cfa_sides, cfa_drinks]
    
    if addons:
        categories.append(cfa_addons)
    
    if desssert:
        categories.append(cfa_desserts)
    
    combinations = itertools.product(*categories)
    return combinations     # returns an iterator object

In [ ]:
iter_cfa_combo_basic = compute_all_cfa_combos()
list_cfa_combo_basic = list(iter_cfa_combo_basic)
print(f"Number of total combinations for Entree + Side + Drink combo: {len(list_cfa_combo_basic)}")

iter_cfa_combo_extra = compute_all_cfa_combos(addons=True, desssert=True)
list_cfa_combo_extra = list(iter_cfa_combo_extra)
print(f"Number of total combinations for Entree, Side, Drink, Dessert and Add-On combo: {len(list_cfa_combo_extra)}")

Number of total combinations for Entree + Side + Drink combo: 62092
Number of total combinations for Entree, Side, Drink, Dessert and Add-On combo: 22353120

## Meal Combination Storage and Computation Ideas

1. Knapsack Approach
    - 0/1 Knapsack problem: 
            
        _"Given two arrays, `profit[]` and `weight[]`, where each element represents the profit and weight of an item respectively, also given an integer `W` representing the maximum capacity of the knapsack (the total weight it can hold)._
        
        _Put the items into the knapsack such that the sum of profits associated with them is the maximum possible, without exceeding the capacity W."_
        
        (https://www.geeksforgeeks.org/dsa/0-1-knapsack-problem-dp-10/)
    - Concern:
        - Knapsack tries to maximize a single value from a pool of items and returns a best solution. We want to hit targets (protein, calories, price) without losing structure to meals (maintain rules with categories).
        - We want to have multiple top picks and rank results. We would have to adjust knapsack to give best k results.
        - Overall, knapsack on its own may not be sufficient for meal building. However, it may have a use when trying to maximize leftover calories.

2. Meal Precomputation
    - Storing every single meal combination is inefficient
    - Recomputing every single meal after a user request is also inefficient
    - Another note: allowing for multiple entrees (maybe max 2-3) can allow for goals to be hit quicker. 
    - Architecture idea:
        1. Precompute entree combinations. Store UID, item IDs, protein total, calorie total, price total
        2. Filter dynamically after user interaction. Use boolen masking/vectorization (quick) to filter for acceptable protein, price, and calorie ranges.
        3. Add on optional sides or drinks (add-ons can come in later).
        4. Apply scoring algorithm.
    - Expansion: add some sort of caching mechanism for common presets