## Load Data

In [4]:
import json
import pandas as pd

with open('../restaurants.menu_item_variations.json', 'r') as file:
    item_list = json.load(file)
file.close()

## Select all Items for Specific Restaurants: Chick-fil-A and Chipotle

In [4]:
chick_fil_a_items = []
chipotle_items = []

for item in item_list:
    if item.get("restaurant_name") == "Chick-fil-A":
        chick_fil_a_items.append(item)

    elif item.get("restaurant_name") == "Chipotle":
        chipotle_items.append(item)

print(f"Number of Chick-fil-A items: {len(chick_fil_a_items)}")
print(f"Number of Chipotle items: {len(chipotle_items)}")

# making dataframes just to visualize easier
df_cfa = pd.DataFrame(chick_fil_a_items)
df_chipotle = pd.DataFrame(chipotle_items)

Number of Chick-fil-A items: 177
Number of Chipotle items: 99

### Visualization

In [ ]:
# Chick fil A items
df_cfa.head()

,item_id,menu_item_id,menu_item_name,restaurant_name,cuisine_type,macronutrient_profile,recipe_items,price,golden_ratio,ai_description,category,allergen_info,nutrition_info,menu_card_image
0,chick_fil_a_chick_n_strips,item_818528ff980240e39250845e28b061f7,Chick-n-Strips,Chick-fil-A,"[American, Fast Food, Southern]","[High Protein, Low Carb, Low Calorie, High Sod...",{},4.29,0.950,"Enjoy tender, hand-breaded Chick-n-Strips, per...",Classic Chicken,"{'contains': ['egg', 'gluten', 'milk', 'wheat'...","{'serving_size': '2 strips', 'calories': 200, ...",https://fastfoodnutrition.org/logos/chick-fil-...
1,chick_fil_a_chicken_nuggets,item_44dbe341c1dd40f095ad04f1bced08e9,Chicken Nuggets,Chick-fil-A,"[American, Fast Food, Southern]","[Low Carb, Low Calorie, High Sodium, Low Sugar]",{},3.49,1.000,"Deliciously crispy, bite-sized chicken nuggets...",Classic Chicken,"{'contains': ['egg', 'gluten', 'milk', 'wheat'...","{'serving_size': '4 nuggets', 'calories': 130,...",https://fastfoodnutrition.org/logos/chick-fil-...
2,chick_fil_a_chicken_nuggets,item_44dbe341c1dd40f095ad04f1bced08e9,Chicken Nuggets,Chick-fil-A,"[American, Fast Food, Southern]","[High Protein, Low Carb, Low Calorie, High Sod...",{},4.99,1.080,"Deliciously crispy, bite-sized chicken nuggets...",Classic Chicken,"{'contains': ['egg', 'gluten', 'milk', 'wheat'...","{'serving_size': '8 nuggets', 'calories': 250,...",https://fastfoodnutrition.org/logos/chick-fil-...
3,chick_fil_a_chicken_nuggets,item_44dbe341c1dd40f095ad04f1bced08e9,Chicken Nuggets,Chick-fil-A,"[American, Fast Food, Southern]","[High Protein, Low Carb, High Calorie, High So...",{},14.99,1.062,"Deliciously crispy, bite-sized chicken nuggets...",Classic Chicken,"{'contains': ['egg', 'gluten', 'milk', 'wheat'...","{'serving_size': '30 nuggets', 'calories': 970...",https://fastfoodnutrition.org/logos/chick-fil-...
4,chick_fil_a_chick_n_strips,item_818528ff980240e39250845e28b061f7,Chick-n-Strips,Chick-fil-A,"[American, Fast Food, Southern]","[High Protein, High Sodium, Low Sugar]",{},6.99,0.951,"Enjoy tender, hand-breaded Chick-n-Strips, per...",Classic Chicken,"{'contains': ['egg', 'gluten', 'milk', 'wheat'...","{'serving_size': '4 strips', 'calories': 410, ...",https://fastfoodnutrition.org/logos/chick-fil-...

In [ ]:
# chipotle items
df_chipotle.head()

,item_id,menu_item_id,menu_item_name,restaurant_name,cuisine_type,macronutrient_profile,recipe_items,price,golden_ratio,ai_description,category,allergen_info,nutrition_info,menu_card_image
0,chipotle_izze_sparkling_blackberry_soda,item_09007bf4a7904846a73f8438b299f460,Izze Sparkling Blackberry Soda,Chipotle,"[Mexican, Latin American, Tex-Mex]","[High Carb, Low Calorie, Low Sodium, Low Sugar]",{},2.50,0.000,Delight in the effervescent zing of Izze Spark...,Beverages,"{'contains': [], 'may_contain': [], 'does_not_...","{'serving_size': '1 bottle', 'calories': 170, ...",https://fastfoodnutrition.org/logos/chipotle.jpg
1,chipotle_tractor_hibiscus_lemonade,item_86b8d873b6f840e4822df75ba6baac51,Tractor Hibiscus Lemonade,Chipotle,"[Mexican, Latin American, Tex-Mex]","[High Carb, Low Calorie, Low Sodium, Low Sugar]",{},3.50,0.000,Quench your thirst with this refreshing hibisc...,Beverages,"{'contains': [], 'may_contain': [], 'does_not_...","{'serving_size': '22 oz', 'calories': 150, 'ch...",https://fastfoodnutrition.org/logos/chipotle.jpg
2,chipotle_chicken_burrito_bowl,item_66a6aa38b02d47208ed7141199aec1e1,Chicken Burrito Bowl,Chipotle,"[Mexican, Latin American, Tex-Mex]","[High Protein, Low Carb, Low Calorie, Low Sugar]",{},8.50,1.684,"Savor a hearty Chicken Burrito Bowl, featuring...",Burrito Bowls,"{'contains': [], 'may_contain': [], 'does_not_...","{'serving_size': '4 oz', 'calories': 190, 'cho...",https://fastfoodnutrition.org/logos/chipotle.jpg
3,chipotle_black_beans,item_1c084543ac7b4259873ac1bf141574e9,Black Beans,Chipotle,"[Mexican, Latin American, Tex-Mex]","[High Carb, Low Calorie, Low Sugar]",{},2.50,0.583,"Savor our hearty black beans, perfectly season...",Extras and Toppings,"{'contains': [], 'may_contain': [], 'does_not_...","{'serving_size': '4 oz', 'calories': 120, 'cho...",https://fastfoodnutrition.org/logos/chipotle.jpg
4,chipotle_carnitas_burrito,item_7d30d25697de4ecdaab8169d37d5e74a,Carnitas Burrito,Chipotle,"[Mexican, Latin American, Tex-Mex]","[High Protein, High Sodium, Low Sugar, Balanced]",{},9.75,0.708,"Savor the tender, slow-cooked carnitas wrapped...",Burritos,"{'contains': ['gluten', 'sulfites', 'wheat'], ...","{'serving_size': '4 oz', 'calories': 480, 'cho...",https://fastfoodnutrition.org/logos/chipotle.jpg

### Categories

Display all categories for Chick fil A and Chipotle.

In [20]:
cfa_categories = df_cfa['category'].unique()
chip_categories = df_chipotle['category'].unique()

print(f"Chick fil A categories: {cfa_categories}")
print(f"Chipotle categories: {chip_categories}")

Chick fil A categories: ['Classic Chicken' 'Beverages' 'Breakfast' 'Desserts' "Kid's Meal"
 'Salad Dressings' 'Cool Wraps' 'Sauces' 'Sides' 'Salads']
Chipotle categories: ['Beverages' 'Burrito Bowls' 'Extras and Toppings' 'Burritos'
 'Quesadillas' 'Salads' 'Tacos' 'Lifestyle Bowls' 'Tortilla Chips']

## Exploring Data

Checking the content of some categories to distinguish what meal component they may be. (Feel free to explore yourself)

In [ ]:
cfa_cat_name = "Breakfast"
display(df_cfa.loc[df_cfa['category'] == cfa_cat_name])

,item_id,menu_item_id,menu_item_name,restaurant_name,cuisine_type,macronutrient_profile,recipe_items,price,golden_ratio,ai_description,category,allergen_info,nutrition_info,menu_card_image
53,chick_fil_a_hash_brown_scramble_burrito,item_57b571666c3e48fc8f253bb0e65e1315,Hash Brown Scramble Burrito,Chick-fil-A,"[American, Fast Food, Southern]","[High Protein, High Fat, High Calorie, High So...",{},4.99,0.486,Savor a hearty breakfast with our Hash Brown S...,Breakfast,"{'contains': ['egg', 'gluten', 'milk', 'soy', ...","{'serving_size': '1 burrito', 'calories': 700,...",https://fastfoodnutrition.org/logos/chick-fil-...
55,chick_fil_a_bacon_egg_cheese_biscuit,item_4113c01c405f4ec5ac415e8ffa67c34d,"Bacon, Egg & Cheese Biscuit",Chick-fil-A,"[American, Fast Food, Southern]","[High Sodium, Low Sugar]",{},3.99,0.357,"Start your day right with a flaky, buttery bis...",Breakfast,"{'contains': ['egg', 'gluten', 'milk', 'soy', ...","{'serving_size': '1 biscuit', 'calories': 420,...",https://fastfoodnutrition.org/logos/chick-fil-...
57,chick_fil_a_chicken_biscuit,item_8c359b035e514162add9db3dfcca12c7,Chicken Biscuit,Chick-fil-A,"[American, Fast Food, Southern]","[High Sodium, Low Sugar]",{},3.99,0.413,Start your day with a flaky buttermilk biscuit...,Breakfast,"{'contains': ['egg', 'gluten', 'milk', 'soy', ...","{'serving_size': '1 biscuit', 'calories': 460,...",https://fastfoodnutrition.org/logos/chick-fil-...
58,chick_fil_a_yogurt_parfait_w_cookie_cumbs,item_696737d778b34b2caf288baebc324099,Yogurt Parfait w/ Cookie Cumbs,Chick-fil-A,"[American, Fast Food, Southern]","[Low Calorie, Low Sodium, Low Sugar]",{},4.99,0.480,Indulge in a creamy yogurt parfait layered wit...,Breakfast,"{'contains': ['gluten', 'milk', 'soy', 'wheat'...","{'serving_size': '1 parfait', 'calories': 250,...",https://fastfoodnutrition.org/logos/chick-fil-...
60,chick_fil_a_egg_cheese_english_muffin,item_07042d87afd04700973507580773663d,Egg & Cheese English Muffin,Chick-fil-A,"[American, Fast Food, Southern]","[Low Calorie, High Sodium, Low Sugar]",{},3.99,0.533,Start your day with a fluffy egg and melted ch...,Breakfast,"{'contains': ['egg', 'gluten', 'milk', 'soy', ...","{'serving_size': '1 sandwich', 'calories': 300...",https://fastfoodnutrition.org/logos/chick-fil-...
61,chick_fil_a_hash_brown_scramble_burrito,item_57b571666c3e48fc8f253bb0e65e1315,Hash Brown Scramble Burrito,Chick-fil-A,"[American, Fast Food, Southern]","[High Protein, High Fat, High Calorie, High So...",{},4.99,0.394,Savor a hearty breakfast with our Hash Brown S...,Breakfast,"{'contains': ['egg', 'gluten', 'milk', 'soy', ...","{'serving_size': '1 burrito', 'calories': 710,...",https://fastfoodnutrition.org/logos/chick-fil-...
62,chick_fil_a_yogurt_parfait_with_harvest_nut_gr...,item_440d8ca23c2b4ecfa16ddc71e9c0d1aa,Yogurt Parfait with Harvest Nut Granola,Chick-fil-A,"[American, Fast Food, Southern]","[Low Calorie, Low Sodium, Low Sugar]",{},4.99,0.464,Start your day with a delightful blend of crea...,Breakfast,"{'contains': ['milk', 'tree nuts'], 'may_conta...","{'serving_size': '1 parfait', 'calories': 280,...",https://fastfoodnutrition.org/logos/chick-fil-...
65,chick_fil_a_egg_white_grill,item_403c6de25b2845a0b3804449be646e8a,Egg White Grill,Chick-fil-A,"[American, Fast Food, Southern]","[High Protein, Low Calorie, High Sodium, Low S...",{},4.99,0.862,"Start your day with our Egg White Grill, featu...",Breakfast,"{'contains': ['egg', 'gluten', 'milk', 'soy', ...","{'serving_size': '1 sandwich', 'calories': 290...",https://fastfoodnutrition.org/logos/chick-fil-...
66,chick_fil_a_hash_brown_scramble_bowl,item_cd3d9826a6cd40e58b2bd0eaf8a084df,Hash Brown Scramble Bowl,Chick-fil-A,"[American, Fast Food, Southern]","[High Protein, Low Carb, High Fat, High Sodium...",{},6.99,0.617,"Savor the hearty Hash Brown Scramble Bowl, fea...",Breakfast,"{'contains': ['egg', 'milk', 'soy'], 'may_cont...","{'serving_size': '1 bowl', 'calories': 470, 'c...",https://fastfoodnutrition.org/logos/chick-fil-...
67,chick_fil_a_chicken_egg_cheese_biscuit,item_be2be90336df444faa0fc92fe6768944,"Chicken, Egg & Cheese Biscuit",Chick-fil-A,"[American, Fast Food, Southern]","[High Protein, High Sodium, Low Sugar]",{},4.99,0.491,Start your day with a flaky biscuit layered wi...,Breakfast,"{'contains': ['egg', 'gluten', 'milk', 'soy', ...","{'serving_size': '206g', 'calories': 530, 'cho...",https://fastfoodnutrition.org/logos/chick-fil-...
68,chick_fil_a_egg_cheese_english_muffin,item_07042d87afd04700973507580773663d,Egg & Cheese English Muffin,Chick-fil-A,"[American, Fast Food, Southern]","[High Fat, High Sodium, Low Sugar]",{},4.99,0.462,Start your day with a fluffy egg and melted ch...,Breakfast,"{'contains': ['egg', 'gluten', 'milk', 'soy', ...","{'serving_size': '1 sandwich', 'calories': 520...",https://fastfoodnutrition.org/logos/chick-fil-...
70,chick_fil_a_hash_brown_scramble_bowl,item_cd3d9826a6cd40e58b2bd0eaf8a084df,Hash Brown Scramble Bowl,Chick-fil-A,"[American, Fast Food, Southern]","[Low Carb, High Fat, High Sodium, Low Sugar]",{},5.99,0.479,"Savor the hearty Hash Brown Scramble Bowl, fea...",Breakfast,"{'contains': ['egg', 'milk', 'soy'], 'may_cont...","{'serving_size': '1 bowl', 'calories': 480, 'c...",https://fastfoodnutrition.org/logos/chick-fil-...
71,chick_fil_a_sausage_egg_and_cheese_biscuit,item_b10274268e6548108b9d1b1058b026e3,Sausage Egg and Cheese Biscuit,Chick-fil-A,"[American, Fast Food, Southern]","[High Fat, High Sodium, Low Sugar]",{},3.99,0.365,Indulge in a flaky buttermilk biscuit layered ...,Breakfast,"{'contains': ['egg', 'gluten', 'milk', 'soy', ...","{'serving_size': '1 biscuit', 'calories': 630,...",https://fastfoodnutrition.org/logos/chick-fil-...
74,chick_fil_a_hot_buttered_biscuit,item_80103285c8bc4f86881e8e077169afe1,Hot Buttered Biscuit,Chick-fil-A,"[American, Fast Food, Southern]","[Low Protein, Low Calorie, High Sodium, Low Su...",{},2.49,0.138,"Indulge in our flaky, warm Hot Buttered Biscui...",Breakfast,"{'contains': ['gluten', 'milk', 'soy', 'wheat'...","{'serving_size': '1 biscuit', 'calories': 290,...",https://fastfoodnutrition.org/logos/chick-fil-...
76,chick_fil_a_chick_n_minis,item_66c20fcaff8644dfa4e339fe9772a52c,Chick-n-Minis,Chick-fil-A,"[American, Fast Food, Southern]","[Low Calorie, High Sodium, Low Sugar]",{},3.99,0.571,"Delight in a warm, fluffy biscuit filled with ...",Breakfast,"{'contains': ['egg', 'gluten', 'milk', 'soy', ...","{'serving_size': '94g', 'calories': 280, 'chol...",https://fastfoodnutrition.org/logos/chick-fil-...
79,chick_fil_a_chick_n_minis,item_66c20fcaff8644dfa4e339fe9772a52c,Chick-n-Minis,Chick-fil-A,"[American, Fast Food, Southern]","[High Protein, High Calorie, High Sodium, Low ...",{},14.99,0.552,"Delight in a warm, fluffy biscuit filled with ...",Breakfast,"{'contains': ['egg', 'gluten', 'milk', 'soy', ...","{'serving_size': '10 sliders', 'calories': 870...",https://fastfoodnutrition.org/logos/chick-fil-...
80,chick_fil_a_hash_brown_scramble_bowl,item_cd3d9826a6cd40e58b2bd0eaf8a084df,Hash Brown Scramble Bowl,Chick-fil-A,"[American, Fast Food, Southern]","[High Protein, Low Carb, High Fat, High Sodium...",{},6.99,0.732,"Savor the hearty Hash Brown Scramble Bowl, fea...",Breakfast,"{'contains': ['egg', 'milk', 'soy'], 'may_cont...","{'serving_size': '1 bowl', 'calories': 410, 'c...",https://fastfoodnutrition.org/logos/chick-fil-...
81,chick_fil_a_hash_brown_scramble_burrito,item_57b571666c3e48fc8f253bb0e65e1315,Hash Brown Scramble Burrito,Chick-fil-A,"[American, Fast Food, Southern]",[],{},4.99,0.000,Savor a hearty breakfast with our Hash Brown S...,Breakfast,"{'contains': ['egg', 'gluten', 'milk', 'soy', ...","{'serving_size': '1 serving', 'calories': 0, '...",https://fastfoodnutrition.org/logos/chick-fil-...
82,chick_fil_a_hash_brown_scramble_burrito,item_57b571666c3e48fc8f253bb0e65e1315,Hash Brown Scramble Burrito,Chick-fil-A,"[American, Fast Food, Southern]","[High Protein, High Sodium, Low Sugar]",{},6.99,0.538,Savor a hearty breakfast with our Hash Brown S...,Breakfast,"{'contains': ['egg', 'gluten', 'milk', 'soy', ...","{'serving_size': '1 burrito', 'calories': 650,...",https://fastfoodnutrition.org/logos/chick-fil-...
86,chick_fil_a_chick_n_minis,item_66c20fcaff8644dfa4e339fe9772a52c,Chick-n-Minis,Chick-fil-A,"[American, Fast Food, Southern]","[High Sodium, Low Sugar, Balanced]",{},4.29,0.568,"Delight in a warm, fluffy biscuit filled with ...",Breakfast,"{'contains': ['egg', 'gluten', 'milk', 'soy', ...","{'serving_size': '126g', 'calories': 370, 'cho...",https://fastfoodnutrition.org/logos/chick-fil-...
87,chick_fil_a_chicken_egg_cheese_muffin,item_a7c5d7c2c4d34bb1b9d1d6172662fd79,"Chicken, Egg, & Cheese Muffin",Chick-fil-A,"[American, Fast Food, Southern]","[High Protein, High Sodium, Low Sugar]",{},4.99,0.643,"Start your day with a savory Chicken, Egg, & C...",Breakfast,"{'contains': ['egg', 'gluten', 'milk', 'soy', ...","{'serving_size': '190g', 'calories': 420, 'cho...",https://fastfoodnutrition.org/logos/chick-fil-...
88,chick_fil_a_english_muffin,item_563cef2dab0c4a04a3b41560ab98967a,English Muffin,Chick-fil-A,"[American, Fast Food, Southern]","[High Carb, Low Calorie, Low Sodium, Low Sugar]",{},2.49,0.357,"Start your day right with a warm, toasted Engl...",Breakfast,"{'contains': ['gluten', 'wheat'], 'may_contain...","{'serving_size': '1 English muffin', 'calories...",https://fastfoodnutrition.org/logos/chick-fil-...
89,chick_fil_a_hash_brown_scramble_bowl,item_cd3d9826a6cd40e58b2bd0eaf8a084df,Hash Brown Scramble Bowl,Chick-fil-A,"[American, Fast Food, Southern]","[High Protein, Low Carb, High Fat, High Sodium...",{},6.99,0.609,"Savor the hearty Hash Brown Scramble Bowl, fea...",Breakfast,"{'contains': ['egg', 'milk', 'soy'], 'may_cont...","{'serving_size': '1 bowl', 'calories': 460, 'c...",https://fastfoodnutrition.org/logos/chick-fil-...
90,chick_fil_a_hash_browns,item_0589871236764832a5e65428d0048eac,Hash Browns,Chick-fil-A,"[American, Fast Food, Southern]","[Low Protein, High Fat, Low Calorie, Low Sugar]",{},2.99,0.111,"Delightfully crispy and golden, our Hash Brown...",Breakfast,"{'contains': [], 'may_contain': [], 'does_not_...","{'serving_size': '77g', 'calories': 270, 'chol...",https://fastfoodnutrition.org/logos/chick-fil-...
92,chick_fil_a_spicy_chicken_biscuit,item_b0056ed759974de0ae0ef93c4bc18032,Spicy Chicken Biscuit,Chick-fil-A,"[American, Fast Food, Southern]","[High Sodium, Low Sugar]",{},4.99,0.395,"Start your day with a spicy, crispy chicken fi...",Breakfast,"{'contains': ['egg', 'gluten', 'milk', 'soy', ...","{'serving_size': '145g', 'calories': 430, 'cho...",https://fastfoodnutrition.org/logos/chick-fil-...

In [29]:
chip_cat_name = "Extras and Toppings"
display(df_chipotle.loc[df_chipotle['category'] == chip_cat_name])

,item_id,menu_item_id,menu_item_name,restaurant_name,cuisine_type,macronutrient_profile,recipe_items,price,golden_ratio,ai_description,category,allergen_info,nutrition_info,menu_card_image
3,chipotle_black_beans,item_1c084543ac7b4259873ac1bf141574e9,Black Beans,Chipotle,"[Mexican, Latin American, Tex-Mex]","[High Carb, Low Calorie, Low Sugar]",{},2.50,0.583,"Savor our hearty black beans, perfectly season...",Extras and Toppings,"{'contains': [], 'may_contain': [], 'does_not_...","{'serving_size': '4 oz', 'calories': 120, 'cho...",https://fastfoodnutrition.org/logos/chipotle.jpg
7,chipotle_brown_rice,item_80106d7d1e8f465987cc8544ded07633,Brown Rice,Chipotle,"[Mexican, Latin American, Tex-Mex]","[High Carb, Low Calorie, Low Sodium, Low Sugar]",{},2.50,0.188,"Fluffy, seasoned brown rice adds a hearty, nut...",Extras and Toppings,"{'contains': [], 'may_contain': [], 'does_not_...","{'serving_size': '4 oz', 'calories': 160, 'cho...",https://fastfoodnutrition.org/logos/chipotle.jpg
19,chipotle_corn_salsa,item_1dded22357514ae29affe59a4926062c,Corn Salsa,Chipotle,"[Mexican, Latin American, Tex-Mex]","[Low Carb, Low Calorie, Low Sugar]",{},2.50,0.375,"Vibrant corn salsa bursting with sweet, crunch...",Extras and Toppings,"{'contains': [], 'may_contain': [], 'does_not_...","{'serving_size': '3.5 oz', 'calories': 80, 'ch...",https://fastfoodnutrition.org/logos/chipotle.jpg
31,chipotle_cheese,item_e8226ffc63c94fb4aa6510c521398c21,Cheese,Chipotle,"[Mexican, Latin American, Tex-Mex]","[Low Carb, High Fat, Low Calorie, Low Sodium, ...",{},1.25,0.800,"Indulge in our rich, melty cheese, a perfect t...",Extras and Toppings,"{'contains': ['milk'], 'may_contain': [], 'doe...","{'serving_size': '1 oz', 'calories': 100, 'cho...",https://fastfoodnutrition.org/logos/chipotle.jpg
35,chipotle_cilantro_lime_cauliflower_rice,item_c4094009cb83456fb0f8a030e6034c3c,Cilantro-Lime Cauliflower Rice,Chipotle,"[Mexican, Latin American, Tex-Mex]","[Low Carb, Low Calorie, Low Sodium, Low Sugar]",{},2.50,0.750,Delight in our zesty cilantro-lime cauliflower...,Extras and Toppings,"{'contains': [], 'may_contain': [], 'does_not_...","{'serving_size': '4 oz', 'calories': 40, 'chol...",https://fastfoodnutrition.org/logos/chipotle.jpg
39,chipotle_fajita_veggies,item_9ad85e1be98346c29ac5c53f3cee724f,Fajita Veggies,Chipotle,"[Mexican, Latin American, Tex-Mex]","[Low Carb, Low Calorie, Low Sodium, Low Sugar]",{},2.50,0.500,Sautéed bell peppers and onions bursting with ...,Extras and Toppings,"{'contains': [], 'may_contain': [], 'does_not_...","{'serving_size': '2.5 oz', 'calories': 20, 'ch...",https://fastfoodnutrition.org/logos/chipotle.jpg
40,chipotle_red_tomatillo_salsa,item_0ec3bfcf1e2145ddbdb7975aa653752a,Red Tomatillo Salsa,Chipotle,"[Mexican, Latin American, Tex-Mex]","[Low Carb, Low Calorie, High Sodium, Low Sugar]",{},1.25,0.500,"Vibrant red tomatillo salsa, bursting with zes...",Extras and Toppings,"{'contains': [], 'may_contain': [], 'does_not_...","{'serving_size': '2 fl oz', 'calories': 40, 'c...",https://fastfoodnutrition.org/logos/chipotle.jpg
41,chipotle_vinaigrette_dressing,item_310d1dc35c3242cfa782160f5f5ac1ad,Vinaigrette Dressing,Chipotle,"[Mexican, Latin American, Tex-Mex]","[Low Protein, Low Carb, High Fat, Low Calorie,...",{},1.50,0.000,Elevate your meal with our zesty vinaigrette d...,Extras and Toppings,"{'contains': ['sulfites'], 'may_contain': [], ...","{'serving_size': '2 fl oz', 'calories': 260, '...",https://fastfoodnutrition.org/logos/chipotle.jpg
42,chipotle_lettuce,item_de98768600e447eab9643f5d1f9f8968,Lettuce,Chipotle,"[Mexican, Latin American, Tex-Mex]","[Low Carb, Low Calorie, Low Sodium, Low Sugar]",{},1.25,1.000,"Crisp, vibrant lettuce adds a refreshing crunc...",Extras and Toppings,"{'contains': [], 'may_contain': [], 'does_not_...","{'serving_size': '2.5 oz', 'calories': 10, 'ch...",https://fastfoodnutrition.org/logos/chipotle.jpg
60,chipotle_sour_cream,item_67fa4d440669461ca097f3eba53bb89d,Sour Cream,Chipotle,"[Mexican, Latin American, Tex-Mex]","[Low Carb, High Fat, Low Calorie, Low Sodium, ...",{},1.25,0.167,Creamy and tangy sour cream that adds a luscio...,Extras and Toppings,"{'contains': [], 'may_contain': [], 'does_not_...","{'serving_size': '2 oz', 'calories': 120, 'cho...",https://fastfoodnutrition.org/logos/chipotle.jpg
62,chipotle_guacamole,item_80a9fb211e604a05a829fcb5bb34f860,Guacamole,Chipotle,"[Mexican, Latin American, Tex-Mex]","[Low Carb, High Fat, Low Calorie, Low Sodium, ...",{},2.50,0.133,"Creamy guacamole made from ripe avocados, zest...",Extras and Toppings,"{'contains': [], 'may_contain': [], 'does_not_...","{'serving_size': '3.5 oz', 'calories': 150, 'c...",https://fastfoodnutrition.org/logos/chipotle.jpg
68,chipotle_green_tomatillo_salsa,item_1b6ed70729ed422ab79ebab1537ec696,Green Tomatillo Salsa,Chipotle,"[Mexican, Latin American, Tex-Mex]","[Low Carb, Low Calorie, Low Sodium, Low Sugar]",{},1.50,0.667,"Vibrant green tomatillo salsa, bursting with z...",Extras and Toppings,"{'contains': [], 'may_contain': [], 'does_not_...","{'serving_size': '2 fl oz', 'calories': 15, 'c...",https://fastfoodnutrition.org/logos/chipotle.jpg
69,chipotle_pinto_beans,item_6fa78e819c6c4f92b90a0e75349b7426,Pinto Beans,Chipotle,"[Mexican, Latin American, Tex-Mex]","[High Carb, Low Calorie, Low Sugar]",{},1.50,0.583,"Tender pinto beans, slow-cooked to perfection,...",Extras and Toppings,"{'contains': [], 'may_contain': [], 'does_not_...","{'serving_size': '4 oz', 'calories': 120, 'cho...",https://fastfoodnutrition.org/logos/chipotle.jpg
72,chipotle_tomato_salsa,item_cb44b62f2a3d4b84883d86db5afaf321,Tomato Salsa,Chipotle,"[Mexican, Latin American, Tex-Mex]","[Low Carb, Low Calorie, High Sodium, Low Sugar]",{},1.50,0.500,Zesty tomato salsa brimming with ripe tomatoes...,Extras and Toppings,"{'contains': [], 'may_contain': [], 'does_not_...","{'serving_size': '3.5 oz', 'calories': 20, 'ch...",https://fastfoodnutrition.org/logos/chipotle.jpg
73,chipotle_white_rice,item_7bed363bbc864ec882abe3bf85422d41,White Rice,Chipotle,"[Mexican, Latin American, Tex-Mex]","[High Carb, Low Calorie, Low Sodium, Low Sugar]",{},2.50,0.176,"Fluffy, perfectly cooked white rice infused wi...",Extras and Toppings,"{'contains': [], 'may_contain': [], 'does_not_...","{'serving_size': '4 oz', 'calories': 170, 'cho...",https://fastfoodnutrition.org/logos/chipotle.jpg
78,chipotle_queso,item_3b24465d136540b288c48444fc91208e,Queso,Chipotle,"[Mexican, Latin American, Tex-Mex]","[Low Carb, High Fat, Low Calorie, Low Sodium, ...",{},2.50,0.500,"Indulge in our velvety queso, a rich blend of ...",Extras and Toppings,"{'contains': ['milk', 'sulfites'], 'may_contai...","{'serving_size': '2 oz', 'calories': 120, 'cho...",https://fastfoodnutrition.org/logos/chipotle.jpg
80,chipotle_supergreens,item_89eb2f3ba4ab4652b2cf8ed07578ea6d,Supergreens,Chipotle,"[Mexican, Latin American, Tex-Mex]","[Low Carb, Low Calorie, Low Sodium, Low Sugar]",{},2.50,0.667,Delight in a vibrant blend of fresh supergreen...,Extras and Toppings,"{'contains': [], 'may_contain': [], 'does_not_...","{'serving_size': '1 serving', 'calories': 15, ...",https://fastfoodnutrition.org/logos/chipotle.jpg

### Some Thoughts After Exploring Data

Issue 1: broader categories like "Kid's Meal" and "Breakfast" in Chick fil A contain items that may be from different categories.
- I'm just going to hard code the differences for this example
    - most items in "Breakfast" category can probably be an "Entree" (with the exception of hash browns)
    - items in the "Kid's Meal" are an entree if they have the word "meal" in the name, "milk" for beverage, and the rest would be sides

Issue 2: when computing combinations in the future, should we try to account for 'realistic' combinations?
- If you order a salad, you would probably want salad dressing to go with it. Blindly assigning meals + sides/add-ons won't always be 'realistic'
- Most likely, you wouldn't want to have salad dressing as an add-on when you ordered a chicken sandwich.

Issue 3: Chipotle is too hard...
- I won't touch this for now

## Assign Meal Categories (Entree, Side, Drink, Dessert, Add-On)
Note: this is hard-coded just to have categories to work with.

### Chick-fil-A
Concern: What to do about something like salad dressings? How would we account for a combination that only makes sense in a certain context?

In [10]:
# add a column for meal categories
df_cfa['meal_category'] = 'temp'

# assign meal categories
# note: hard-coded assignment for this one restaurant

entree_categories = ['Classic Chicken', 'Breakfast', 'Cool Wraps', 'Salads', ]
df_cfa.loc[df_cfa['category'].isin(entree_categories), 'meal_category'] = 'Entree'

df_cfa.loc[df_cfa['category'] == 'Sides', 'meal_category'] = 'Side'

df_cfa.loc[df_cfa['category'] == 'Beverages', 'meal_category'] = 'Drink'

df_cfa.loc[df_cfa['category'] == 'Desserts', 'meal_category'] = 'Dessert'

addon_categories = ['Salad Dressings', 'Sauces']
df_cfa.loc[df_cfa['category'].isin(addon_categories), 'meal_category'] = 'Add-On'

# assigning some categories manually
df_cfa.loc[90, 'meal_category'] = 'Side'

kid_mask = df_cfa['category'] == "Kid's Meal"
df_cfa.loc[kid_mask & df_cfa['menu_item_name'].str.contains('Meal', case=False, na=False),'meal_category'] = 'Entree'
df_cfa.loc[kid_mask & df_cfa['menu_item_name'].str.contains('Milk', case=False, na=False),'meal_category'] = 'Drink'
df_cfa.loc[kid_mask & ~df_cfa['menu_item_name'].str.contains('Meal|Milk', case=False, na=False),'meal_category'] = 'Side'

In [16]:
# check that all items got assigned a category
display(df_cfa.loc[df_cfa['meal_category'] == 'temp'])

Empty DataFrame
Columns: [item_id, menu_item_id, menu_item_name, restaurant_name, cuisine_type, macronutrient_profile, recipe_items, price, golden_ratio, ai_description, category, allergen_info, nutrition_info, menu_card_image, meal_category]
Index: []

In [13]:
# sort menu items for CFA by meal category
# placeholder: storing menu items just by their ID

cfa_entrees = list(df_cfa.loc[df_cfa['meal_category'] == 'Entree', 'menu_item_id'])
cfa_sides = list(df_cfa.loc[df_cfa['meal_category'] == 'Side', 'menu_item_id'])
cfa_drinks = list(df_cfa.loc[df_cfa['meal_category'] == 'Drink', 'menu_item_id'])
cfa_desserts = list(df_cfa.loc[df_cfa['meal_category'] == 'Dessert', 'menu_item_id'])
cfa_addons = list(df_cfa.loc[df_cfa['meal_category'] == 'Add-On', 'menu_item_id'])

print(f"Count of Entrees: {len(cfa_entrees)}")
print(f"Count of Sides: {len(cfa_sides)}")
print(f"Count of Drinks: {len(cfa_drinks)}")
print(f"Count of Desserts: {len(cfa_desserts)}")
print(f"Count of Add-Ons: {len(cfa_addons)}")

Count of Entrees: 76
Count of Sides: 19
Count of Drinks: 43
Count of Desserts: 24
Count of Add-Ons: 15

## Meal Combination Exploration

Information to calculate when storing meals:
- calories
- protein
- price

In [1]:
import itertools

In [ ]:
# forcing the combo to at least have Entree, Side, and Drink
def compute_cfa_combos(addons=False, desssert=False):
    categories = [cfa_entrees, cfa_sides, cfa_drinks]
    
    if addons:
        categories.append(cfa_addons)
    
    if desssert:
        categories.append(cfa_desserts)
    
    combinations = itertools.product(*categories)
    return combinations     # returns an iterator object

In [18]:
iter_cfa_combo_basic = compute_cfa_combos()
list_cfa_combo_basic = list(iter_cfa_combo_basic)
print(f"Number of total combinations for Entree + Side + Drink combo: {len(list_cfa_combo_basic)}")

iter_cfa_combo_extra = compute_cfa_combos(addons=True, desssert=True)
list_cfa_combo_extra = list(iter_cfa_combo_extra)
print(f"Number of total combinations for Entree, Side, Drink, Dessert and Add-On combo: {len(list_cfa_combo_extra)}")

Number of total combinations for Entree + Side + Drink combo: 62092
Number of total combinations for Entree, Side, Drink, Dessert and Add-On combo: 22353120