# Meal Combination Sandbox
_Disclaimer: This code is not final, but just an exploration. The storage and data structures used are simply for the purpose of this notebook._

## Load Data

In [2]:
import json
import pandas as pd

with open('../restaurants.menu_item_variations.json', 'r') as file:
    item_list = json.load(file)
file.close()

## Select all Items for Specific Restaurants: Chick-fil-A, Taco Bell, and Chipotle

In [8]:
chick_fil_a_items = []
tacobell_items = []
chipotle_items = []

for item in item_list:
    if item.get("restaurant_name") == "Chick-fil-A":
        chick_fil_a_items.append(item)

    elif item.get("restaurant_name") == "Taco Bell":
        tacobell_items.append(item)
    
    elif item.get("restaurant_name") == "Chipotle":
        chipotle_items.append(item)

print(f"Number of Chick-fil-A items: {len(chick_fil_a_items)}")
print(f"Number of Taco Bell items: {len(tacobell_items)}")
print(f"Number of Chipotle items: {len(chipotle_items)}")

# making dataframes just to visualize easier
df_cfa = pd.DataFrame(chick_fil_a_items)
df_tb = pd.DataFrame(tacobell_items)
df_chipotle = pd.DataFrame(chipotle_items)

Number of Chick-fil-A items: 177
Number of Taco Bell items: 205
Number of Chipotle items: 99

In [9]:
# extract nutrition information as columns
def extract_nutrition(df):
    nutrition_df = df["nutrition_info"].apply(pd.Series)
    df = pd.concat([df.drop(columns=["nutrition_info"]), nutrition_df], axis=1)
    return df

df_cfa = extract_nutrition(df_cfa)
df_tb = extract_nutrition(df_tb)
df_chipotle = extract_nutrition(df_chipotle)

### Visualization

In [10]:
# Chick fil A items
df_cfa.head()

,item_id,menu_item_id,menu_item_name,restaurant_name,cuisine_type,macronutrient_profile,recipe_items,price,golden_ratio,ai_description,...,serving_size,calories,cholesterol,sodium,total_carbohydrates,dietary_fiber,sugars,protein,potassium,total_fat
0,chick_fil_a_chick_n_strips,item_818528ff980240e39250845e28b061f7,Chick-n-Strips,Chick-fil-A,"[American, Fast Food, Southern]","[High Protein, Low Carb, Low Calorie, High Sod...",{},4.29,0.950,"Enjoy tender, hand-breaded Chick-n-Strips, per...",...,2 strips,200,50,580,11,0,1,19,0,9
1,chick_fil_a_chicken_nuggets,item_44dbe341c1dd40f095ad04f1bced08e9,Chicken Nuggets,Chick-fil-A,"[American, Fast Food, Southern]","[Low Carb, Low Calorie, High Sodium, Low Sugar]",{},3.49,1.000,"Deliciously crispy, bite-sized chicken nuggets...",...,4 nuggets,130,40,610,5,0,0,13,0,6
2,chick_fil_a_chicken_nuggets,item_44dbe341c1dd40f095ad04f1bced08e9,Chicken Nuggets,Chick-fil-A,"[American, Fast Food, Southern]","[High Protein, Low Carb, Low Calorie, High Sod...",{},4.99,1.080,"Deliciously crispy, bite-sized chicken nuggets...",...,8 nuggets,250,85,1210,11,0,1,27,0,11
3,chick_fil_a_chicken_nuggets,item_44dbe341c1dd40f095ad04f1bced08e9,Chicken Nuggets,Chick-fil-A,"[American, Fast Food, Southern]","[High Protein, Low Carb, High Calorie, High So...",{},14.99,1.062,"Deliciously crispy, bite-sized chicken nuggets...",...,30 nuggets,970,285,3660,35,4,1,103,0,46
4,chick_fil_a_chick_n_strips,item_818528ff980240e39250845e28b061f7,Chick-n-Strips,Chick-fil-A,"[American, Fast Food, Southern]","[High Protein, High Sodium, Low Sugar]",{},6.99,0.951,"Enjoy tender, hand-breaded Chick-n-Strips, per...",...,4 strips,410,100,1150,22,0,2,39,0,19

In [11]:
# Taco Bell items
df_tb.head()

,item_id,menu_item_id,menu_item_name,restaurant_name,cuisine_type,macronutrient_profile,recipe_items,price,golden_ratio,ai_description,...,serving_size,calories,cholesterol,sodium,total_carbohydrates,dietary_fiber,sugars,protein,potassium,total_fat
0,taco_bell_bean_burrito,item_bc872feac0cd4c038de6a4bc27b91eef,Bean Burrito,Taco Bell,"[Mexican, American, Fast Food]","[High Carb, Low Calorie, High Sodium, Low Sugar]",{},1.29,0.371,Savor the hearty blend of seasoned refried bea...,...,1 burrito,350,5,1000,54,11,3,13,0,9
1,taco_bell_beefy_5_layer_burrito,item_68a8b72cef0e4ac9acf2b3cb8445ef23,Beefy 5-Layer Burrito,Taco Bell,"[Mexican, American, Fast Food]","[High Sodium, Low Sugar]",{},2.99,0.367,"Indulge in a hearty Beefy 5-Layer Burrito, pac...",...,1 burrito,490,30,1250,63,9,5,18,0,18
2,taco_bell_burrito_supreme_chicken,item_d8bbc465a2ff443f99500235a73971c9,Burrito Supreme - Chicken,Taco Bell,"[Mexican, American, Fast Food]","[High Sodium, Low Sugar]",{},3.99,0.514,Savor the Burrito Supreme filled with tender c...,...,1 burrito,370,35,1110,49,8,4,19,0,11
3,taco_bell_chicken_enchilada_burrito,item_2185ad40296c41209c67ba5496401929,Chicken Enchilada Burrito,Taco Bell,"[Mexican, American, Fast Food]","[High Sodium, Low Sugar]",{},3.99,0.500,Savor the bold flavors of our Chicken Enchilad...,...,1 burrito,380,40,1150,49,3,3,19,0,12
4,taco_bell_coffee_with_creamer,item_1aaeafaf9be14badb5ce82fcd2e2aaaa,Coffee with Creamer,Taco Bell,"[Mexican, American, Fast Food]","[Low Carb, Low Calorie, Low Sodium, Low Sugar]",{},2.49,0.667,Savor the smooth blend of rich coffee and crea...,...,1 coffee,30,0,0,3,0,3,2,0,2

In [12]:
# chipotle items
df_chipotle.head()

,item_id,menu_item_id,menu_item_name,restaurant_name,cuisine_type,macronutrient_profile,recipe_items,price,golden_ratio,ai_description,...,serving_size,calories,cholesterol,sodium,total_carbohydrates,dietary_fiber,sugars,protein,potassium,total_fat
0,chipotle_izze_sparkling_blackberry_soda,item_09007bf4a7904846a73f8438b299f460,Izze Sparkling Blackberry Soda,Chipotle,"[Mexican, Latin American, Tex-Mex]","[High Carb, Low Calorie, Low Sodium, Low Sugar]",{},2.50,0.000,Delight in the effervescent zing of Izze Spark...,...,1 bottle,170,0,35,41,0,39,0,0,0
1,chipotle_tractor_hibiscus_lemonade,item_86b8d873b6f840e4822df75ba6baac51,Tractor Hibiscus Lemonade,Chipotle,"[Mexican, Latin American, Tex-Mex]","[High Carb, Low Calorie, Low Sodium, Low Sugar]",{},3.50,0.000,Quench your thirst with this refreshing hibisc...,...,22 oz,150,0,0,36,0,35,0,0,0
2,chipotle_chicken_burrito_bowl,item_66a6aa38b02d47208ed7141199aec1e1,Chicken Burrito Bowl,Chipotle,"[Mexican, Latin American, Tex-Mex]","[High Protein, Low Carb, Low Calorie, Low Sugar]",{},8.50,1.684,"Savor a hearty Chicken Burrito Bowl, featuring...",...,4 oz,190,115,370,1,0,1,32,0,7
3,chipotle_black_beans,item_1c084543ac7b4259873ac1bf141574e9,Black Beans,Chipotle,"[Mexican, Latin American, Tex-Mex]","[High Carb, Low Calorie, Low Sugar]",{},2.50,0.583,"Savor our hearty black beans, perfectly season...",...,4 oz,120,0,250,23,11,0,7,0,1
4,chipotle_carnitas_burrito,item_7d30d25697de4ecdaab8169d37d5e74a,Carnitas Burrito,Chipotle,"[Mexican, Latin American, Tex-Mex]","[High Protein, High Sodium, Low Sugar, Balanced]",{},9.75,0.708,"Savor the tender, slow-cooked carnitas wrapped...",...,4 oz,480,70,1210,45,2,0,34,0,17

### Categories

Display all categories for Chick-fil-A, Taco Bell, and Chipotle.

In [5]:
cfa_categories = df_cfa['category'].unique()
tb_categories = df_tb['category'].unique()
chip_categories = df_chipotle['category'].unique()

print(f"Chick fil A categories: {cfa_categories}")
print(f"Taco Bell categories: {tb_categories}")
print(f"Chipotle categories: {chip_categories}")

Chick fil A categories: ['Classic Chicken' 'Beverages' 'Breakfast' 'Desserts' "Kid's Meal"
 'Salad Dressings' 'Cool Wraps' 'Sauces' 'Sides' 'Salads']
Taco Bell categories: ['Burritos' 'Beverages' 'Tacos' 'Breakfast' 'Cantina Chicken'
 'Condiments & Sauces' 'Chalupas' 'Nachos' 'Sides' 'Specialties']
Chipotle categories: ['Beverages' 'Burrito Bowls' 'Extras and Toppings' 'Burritos'
 'Quesadillas' 'Salads' 'Tacos' 'Lifestyle Bowls' 'Tortilla Chips']

## Exploring Data

Checking the content of some categories to distinguish what meal component they may be. (Feel free to explore yourself)

### Chick-fil-A Data

In [13]:
'''Chick fil A categories: ['Classic Chicken' 'Beverages' 'Breakfast' 'Desserts' "Kid's Meal"
 'Salad Dressings' 'Cool Wraps' 'Sauces' 'Sides' 'Salads']'''

cfa_cat_name = "Breakfast"
display(df_cfa.loc[df_cfa['category'] == cfa_cat_name])

,item_id,menu_item_id,menu_item_name,restaurant_name,cuisine_type,macronutrient_profile,recipe_items,price,golden_ratio,ai_description,...,serving_size,calories,cholesterol,sodium,total_carbohydrates,dietary_fiber,sugars,protein,potassium,total_fat
53,chick_fil_a_hash_brown_scramble_burrito,item_57b571666c3e48fc8f253bb0e65e1315,Hash Brown Scramble Burrito,Chick-fil-A,"[American, Fast Food, Southern]","[High Protein, High Fat, High Calorie, High So...",{},4.99,0.486,Savor a hearty breakfast with our Hash Brown S...,...,1 burrito,700,415,1750,51,3,2,34,0,40
55,chick_fil_a_bacon_egg_cheese_biscuit,item_4113c01c405f4ec5ac415e8ffa67c34d,"Bacon, Egg & Cheese Biscuit",Chick-fil-A,"[American, Fast Food, Southern]","[High Sodium, Low Sugar]",{},3.99,0.357,"Start your day right with a flaky, buttery bis...",...,1 biscuit,420,180,1290,38,2,4,15,0,23
57,chick_fil_a_chicken_biscuit,item_8c359b035e514162add9db3dfcca12c7,Chicken Biscuit,Chick-fil-A,"[American, Fast Food, Southern]","[High Sodium, Low Sugar]",{},3.99,0.413,Start your day with a flaky buttermilk biscuit...,...,1 biscuit,460,45,1510,45,2,6,19,0,23
58,chick_fil_a_yogurt_parfait_w_cookie_cumbs,item_696737d778b34b2caf288baebc324099,Yogurt Parfait w/ Cookie Cumbs,Chick-fil-A,"[American, Fast Food, Southern]","[Low Calorie, Low Sodium, Low Sugar]",{},4.99,0.480,Indulge in a creamy yogurt parfait layered wit...,...,1 parfait,250,15,85,33,1,26,12,0,8
60,chick_fil_a_egg_cheese_english_muffin,item_07042d87afd04700973507580773663d,Egg & Cheese English Muffin,Chick-fil-A,"[American, Fast Food, Southern]","[Low Calorie, High Sodium, Low Sugar]",{},3.99,0.533,Start your day with a fluffy egg and melted ch...,...,1 sandwich,300,180,800,29,1,2,16,0,14
61,chick_fil_a_hash_brown_scramble_burrito,item_57b571666c3e48fc8f253bb0e65e1315,Hash Brown Scramble Burrito,Chick-fil-A,"[American, Fast Food, Southern]","[High Protein, High Fat, High Calorie, High So...",{},4.99,0.394,Savor a hearty breakfast with our Hash Brown S...,...,1 burrito,710,395,1440,46,3,1,28,0,46
62,chick_fil_a_yogurt_parfait_with_harvest_nut_gr...,item_440d8ca23c2b4ecfa16ddc71e9c0d1aa,Yogurt Parfait with Harvest Nut Granola,Chick-fil-A,"[American, Fast Food, Southern]","[Low Calorie, Low Sodium, Low Sugar]",{},4.99,0.464,Start your day with a delightful blend of crea...,...,1 parfait,280,15,85,37,1,27,13,0,8
65,chick_fil_a_egg_white_grill,item_403c6de25b2845a0b3804449be646e8a,Egg White Grill,Chick-fil-A,"[American, Fast Food, Southern]","[High Protein, Low Calorie, High Sodium, Low S...",{},4.99,0.862,"Start your day with our Egg White Grill, featu...",...,1 sandwich,290,60,970,29,1,2,25,0,8
66,chick_fil_a_hash_brown_scramble_bowl,item_cd3d9826a6cd40e58b2bd0eaf8a084df,Hash Brown Scramble Bowl,Chick-fil-A,"[American, Fast Food, Southern]","[High Protein, Low Carb, High Fat, High Sodium...",{},6.99,0.617,"Savor the hearty Hash Brown Scramble Bowl, fea...",...,1 bowl,470,415,1340,19,2,2,29,0,30
67,chick_fil_a_chicken_egg_cheese_biscuit,item_be2be90336df444faa0fc92fe6768944,"Chicken, Egg & Cheese Biscuit",Chick-fil-A,"[American, Fast Food, Southern]","[High Protein, High Sodium, Low Sugar]",{},4.99,0.491,Start your day with a flaky biscuit layered wi...,...,206g,530,215,1830,45,2,7,26,0,27
68,chick_fil_a_egg_cheese_english_muffin,item_07042d87afd04700973507580773663d,Egg & Cheese English Muffin,Chick-fil-A,"[American, Fast Food, Southern]","[High Fat, High Sodium, Low Sugar]",{},4.99,0.462,Start your day with a fluffy egg and melted ch...,...,1 sandwich,520,210,1060,30,1,2,24,0,34
70,chick_fil_a_hash_brown_scramble_bowl,item_cd3d9826a6cd40e58b2bd0eaf8a084df,Hash Brown Scramble Bowl,Chick-fil-A,"[American, Fast Food, Southern]","[Low Carb, High Fat, High Sodium, Low Sugar]",{},5.99,0.479,"Savor the hearty Hash Brown Scramble Bowl, fea...",...,1 bowl,480,395,1010,15,2,1,23,0,37
71,chick_fil_a_sausage_egg_and_cheese_biscuit,item_b10274268e6548108b9d1b1058b026e3,Sausage Egg and Cheese Biscuit,Chick-fil-A,"[American, Fast Food, Southern]","[High Fat, High Sodium, Low Sugar]",{},3.99,0.365,Indulge in a flaky buttermilk biscuit layered ...,...,1 biscuit,630,210,1540,38,2,4,23,0,43
74,chick_fil_a_hot_buttered_biscuit,item_80103285c8bc4f86881e8e077169afe1,Hot Buttered Biscuit,Chick-fil-A,"[American, Fast Food, Southern]","[Low Protein, Low Calorie, High Sodium, Low Su...",{},2.49,0.138,"Indulge in our flaky, warm Hot Buttered Biscui...",...,1 biscuit,290,0,760,37,2,4,4,0,15
76,chick_fil_a_chick_n_minis,item_66c20fcaff8644dfa4e339fe9772a52c,Chick-n-Minis,Chick-fil-A,"[American, Fast Food, Southern]","[Low Calorie, High Sodium, Low Sugar]",{},3.99,0.571,"Delight in a warm, fluffy biscuit filled with ...",...,94g,280,40,650,30,1,5,16,0,10
79,chick_fil_a_chick_n_minis,item_66c20fcaff8644dfa4e339fe9772a52c,Chick-n-Minis,Chick-fil-A,"[American, Fast Food, Southern]","[High Protein, High Calorie, High Sodium, Low ...",{},14.99,0.552,"Delight in a warm, fluffy biscuit filled with ...",...,10 sliders,870,130,2150,92,5,14,48,0,35
80,chick_fil_a_hash_brown_scramble_bowl,item_cd3d9826a6cd40e58b2bd0eaf8a084df,Hash Brown Scramble Bowl,Chick-fil-A,"[American, Fast Food, Southern]","[High Protein, Low Carb, High Fat, High Sodium...",{},6.99,0.732,"Savor the hearty Hash Brown Scramble Bowl, fea...",...,1 bowl,410,415,1190,15,2,2,30,0,26
81,chick_fil_a_hash_brown_scramble_burrito,item_57b571666c3e48fc8f253bb0e65e1315,Hash Brown Scramble Burrito,Chick-fil-A,"[American, Fast Food, Southern]",[],{},4.99,0.000,Savor a hearty breakfast with our Hash Brown S...,...,1 serving,0,0,0,0,0,0,0,0,0
82,chick_fil_a_hash_brown_scramble_burrito,item_57b571666c3e48fc8f253bb0e65e1315,Hash Brown Scramble Burrito,Chick-fil-A,"[American, Fast Food, Southern]","[High Protein, High Sodium, Low Sugar]",{},6.99,0.538,Savor a hearty breakfast with our Hash Brown S...,...,1 burrito,650,415,1620,46,3,2,35,0,36
86,chick_fil_a_chick_n_minis,item_66c20fcaff8644dfa4e339fe9772a52c,Chick-n-Minis,Chick-fil-A,"[American, Fast Food, Southern]","[High Sodium, Low Sugar, Balanced]",{},4.29,0.568,"Delight in a warm, fluffy biscuit filled with ...",...,126g,370,50,870,41,2,7,21,0,14
87,chick_fil_a_chicken_egg_cheese_muffin,item_a7c5d7c2c4d34bb1b9d1d6172662fd79,"Chicken, Egg, & Cheese Muffin",Chick-fil-A,"[American, Fast Food, Southern]","[High Protein, High Sodium, Low Sugar]",{},4.99,0.643,"Start your day with a savory Chicken, Egg, & C...",...,190g,420,215,1350,37,1,4,27,0,19
88,chick_fil_a_english_muffin,item_563cef2dab0c4a04a3b41560ab98967a,English Muffin,Chick-fil-A,"[American, Fast Food, Southern]","[High Carb, Low Calorie, Low Sodium, Low Sugar]",{},2.49,0.357,"Start your day right with a warm, toasted Engl...",...,1 English muffin,140,0,220,29,1,1,5,0,2
89,chick_fil_a_hash_brown_scramble_bowl,item_cd3d9826a6cd40e58b2bd0eaf8a084df,Hash Brown Scramble Bowl,Chick-fil-A,"[American, Fast Food, Southern]","[High Protein, Low Carb, High Fat, High Sodium...",{},6.99,0.609,"Savor the hearty Hash Brown Scramble Bowl, fea...",...,1 bowl,460,405,1360,19,2,2,28,0,30
90,chick_fil_a_hash_browns,item_0589871236764832a5e65428d0048eac,Hash Browns,Chick-fil-A,"[American, Fast Food, Southern]","[Low Protein, High Fat, Low Calorie, Low Sugar]",{},2.99,0.111,"Delightfully crispy and golden, our Hash Brown...",...,77g,270,0,440,23,3,0,3,0,18
92,chick_fil_a_spicy_chicken_biscuit,item_b0056ed759974de0ae0ef93c4bc18032,Spicy Chicken Biscuit,Chick-fil-A,"[American, Fast Food, Southern]","[High Sodium, Low Sugar]",{},4.99,0.395,"Start your day with a spicy, crispy chicken fi...",...,145g,430,30,1300,43,2,5,17,0,21

### Taco Bell Data

In [14]:
'''Taco Bell categories: ['Burritos' 'Beverages' 'Tacos' 'Breakfast' 'Cantina Chicken'
 'Condiments & Sauces' 'Chalupas' 'Nachos' 'Sides' 'Specialties']'''

tb_cat_name = "Condiments & Sauces"
display(df_tb.loc[df_tb['category'] == tb_cat_name])

,item_id,menu_item_id,menu_item_name,restaurant_name,cuisine_type,macronutrient_profile,recipe_items,price,golden_ratio,ai_description,...,serving_size,calories,cholesterol,sodium,total_carbohydrates,dietary_fiber,sugars,protein,potassium,total_fat
129,taco_bell_mild_sauce,item_b1a34e10fe684507b6e87b1a29dc95e6,Mild Sauce,Taco Bell,"[Mexican, American, Fast Food]",[],{},1.00,0.000,Add a zesty kick to your meal with Taco Bell's...,...,1 packet,0,0,30,0,0,0,0,0,0
131,taco_bell_breakfast_salsa,item_ee95089c94294d589ac6839024ae4ecb,Breakfast Salsa,Taco Bell,"[Mexican, American, Fast Food]","[Low Carb, Low Calorie, Low Sodium, Low Sugar]",{},1.00,0.000,Elevate your breakfast with Taco Bell's zesty ...,...,1 packet,0,0,50,1,0,0,0,0,0
132,taco_bell_nugget_dipping_sauce,item_2ebeb298d6cc4d98b88fc6ad8a9db7dc,Nugget Dipping Sauce,Taco Bell,"[Mexican, American, Fast Food]","[Low Carb, High Fat, Low Calorie, Low Sodium, ...",{},1.00,0.000,"Delightfully creamy and savory, this rich nugg...",...,1.5 oz,200,5,160,8,0,7,0,0,19
133,taco_bell_pepper_jack_sauce,item_b076a600c6584b8f9234c6f9a40d9780,Pepper Jack Sauce,Taco Bell,"[Mexican, American, Fast Food]","[Low Carb, High Fat, Low Calorie, Low Sodium, ...",{},1.00,0.000,Spice up your meal with our zesty Pepper Jack ...,...,14g,70,5,50,1,0,0,0,0,7
134,taco_bell_premium_guacamole_dip,item_57756f900d064b1c8acc474e942926d8,Premium Guacamole Dip,Taco Bell,"[Mexican, American, Fast Food]","[Low Carb, High Fat, Low Calorie, Low Sodium, ...",{},1.49,0.143,"Savor the creamy, fresh taste of our Premium G...",...,43g,70,0,210,3,2,0,1,0,6
136,taco_bell_creamy_jalapeno_sauce,item_21f4680809bf4371bb5548cc92c355ad,Creamy Jalapeno Sauce,Taco Bell,"[Mexican, American, Fast Food]","[Low Carb, High Fat, Low Calorie, Low Sodium, ...",{},1.00,0.000,Elevate your meal with our luscious creamy jal...,...,14g,70,0,50,1,0,1,0,0,7
137,taco_bell_red_sauce,item_25816abada984710ad3583e845c86afb,Red Sauce,Taco Bell,"[Mexican, American, Fast Food]","[Low Carb, Low Calorie, Low Sodium, Low Sugar]",{},1.00,0.000,Elevate your meal with Taco Bell's zesty Red S...,...,28g,10,0,170,2,0,0,0,0,0
138,taco_bell_reduced_fat_sour_cream_dip,item_550942d163114ef9b28c00a7059833cf,Reduced-Fat Sour Cream Dip,Taco Bell,"[Mexican, American, Fast Food]","[Low Carb, High Fat, Low Calorie, Low Sodium, ...",{},1.49,0.167,Indulge guilt-free in our Reduced-Fat Sour Cre...,...,43g,60,10,45,4,0,2,1,0,4
139,taco_bell_salsa,item_de49ee06b6754e869f52d8121a22a6c8,Salsa,Taco Bell,"[Mexican, American, Fast Food]","[Low Carb, Low Calorie, Low Sodium, Low Sugar]",{},1.00,0.000,"Zesty and vibrant, our fresh salsa bursts with...",...,21g,5,0,80,1,0,1,0,0,0
142,taco_bell_hot_sauce,item_d485a1a5657a47d9b7d8b9be477d9a0b,Hot Sauce,Taco Bell,"[Mexican, American, Fast Food]",[],{},1.00,0.000,Elevate your meal with Taco Bell's zesty Hot S...,...,1 packet,0,0,45,0,0,0,0,0,0
143,taco_bell_nugget_dipping_sauce,item_2ebeb298d6cc4d98b88fc6ad8a9db7dc,Nugget Dipping Sauce,Taco Bell,"[Mexican, American, Fast Food]","[Low Carb, High Fat, Low Calorie, Low Sodium, ...",{},1.00,0.000,"Delightfully creamy and savory, this rich nugg...",...,1.5 oz,210,10,210,5,1,4,0,60,21
145,taco_bell_diablo_sauce,item_89e18e63e25242a78c7bbb6a8670e02f,Diablo Sauce,Taco Bell,"[Mexican, American, Fast Food]",[],{},1.00,0.000,"Experience the fiery kick of Diablo Sauce, a b...",...,1 packet,0,0,30,0,0,0,0,0,0
146,taco_bell_salsa_verde,item_b53e9d3fe55d416d84f42e910db685ce,Salsa Verde,Taco Bell,"[Mexican, American, Fast Food]","[Low Carb, Low Calorie, Low Sodium, Low Sugar]",{},1.00,0.000,Bright and zesty Salsa Verde bursts with fresh...,...,6g,5,0,55,1,0,0,0,0,0
149,taco_bell_cilantro_dressing,item_f65327221b254042b242e76fd96045e4,Cilantro Dressing,Taco Bell,"[Mexican, American, Fast Food]","[Low Carb, High Fat, Low Calorie, Low Sodium, ...",{},1.00,0.000,Zesty cilantro dressing brings a burst of vibr...,...,28g,90,10,210,2,0,0,0,0,9
150,taco_bell_green_tomatillo_sauce,item_5a84f49c2b2048009b73e4875fc13443,Green Tomatillo Sauce,Taco Bell,"[Mexican, American, Fast Food]","[Low Carb, Low Calorie, Low Sodium, Low Sugar]",{},1.00,0.000,Zesty green tomatillo sauce bursts with vibran...,...,28g,10,0,170,2,0,1,0,0,0
151,taco_bell_guacamole,item_3673039a1d96483fa6bafd1219f8a2a5,Guacamole,Taco Bell,"[Mexican, American, Fast Food]","[Low Carb, High Fat, Low Calorie, Low Sodium, ...",{},1.49,0.000,"Smooth, creamy guacamole made from ripe avocad...",...,21g,35,0,105,2,1,0,0,0,3
152,taco_bell_nugget_dipping_sauce,item_2ebeb298d6cc4d98b88fc6ad8a9db7dc,Nugget Dipping Sauce,Taco Bell,"[Mexican, American, Fast Food]","[Low Carb, High Fat, Low Calorie, Low Sodium, ...",{},1.00,0.000,"Delightfully creamy and savory, this rich nugg...",...,1.5 oz,210,15,200,3,0,1,0,2,22
156,taco_bell_pico_de_gallo,item_224b6c9b78004f0195c008c797cd9ae9,Pico de Gallo,Taco Bell,"[Mexican, American, Fast Food]","[Low Carb, Low Calorie, Low Sodium, Low Sugar]",{},1.29,0.000,"Zesty pico de gallo featuring diced tomatoes, ...",...,21g,5,0,35,1,0,1,0,0,0
157,taco_bell_salsa_dip,item_845c7684c2ab4c758dad9635386cb1f3,Salsa Dip,Taco Bell,"[Mexican, American, Fast Food]","[Low Carb, Low Calorie, Low Sodium, Low Sugar]",{},1.49,0.000,"Zesty and vibrant, our Salsa Dip blends ripe t...",...,43g,10,0,220,2,0,1,0,0,0
158,taco_bell_reduced_fat_sour_cream,item_10f9e73cfcab46b0b6a6a8c349dafbce,Reduced Fat Sour Cream,Taco Bell,"[Mexican, American, Fast Food]","[Low Carb, High Fat, Low Calorie, Low Sodium, ...",{},1.00,0.333,Creamy and tangy reduced fat sour cream adds a...,...,21g,30,5,20,2,0,1,1,0,2
161,taco_bell_fire_sauce,item_f0d2b6bd85e644c180f213f736f88dab,Fire Sauce,Taco Bell,"[Mexican, American, Fast Food]",[],{},1.00,0.000,"Add a fiery kick to your meal with this bold, ...",...,1 packet,0,0,55,0,0,0,0,0,0
167,taco_bell_spicy_ranch_dip,item_7e8438a5632c4accaf0a34184bf3de7b,Spicy Ranch Dip,Taco Bell,"[Mexican, American, Fast Food]","[Low Carb, High Fat, Low Calorie, Low Sugar, K...",{},1.49,0.043,"Indulge in this creamy, zesty dip infused with...",...,43g,230,20,280,2,0,2,1,0,24
168,taco_bell_nacho_cheese_dip,item_90e6b83a5351467a89d238d4761ac5a2,Nacho Cheese Dip,Taco Bell,"[Mexican, American, Fast Food]","[Low Carb, High Fat, Low Calorie, Low Sugar, K...",{},1.49,0.600,"Indulge in our creamy Nacho Cheese Dip, a velv...",...,40g,150,35,250,2,1,0,9,0,12
169,taco_bell_pizza_sauce,item_173cbf2ddce147b180cfea34697b6cb1,Pizza Sauce,Taco Bell,"[Mexican, American, Fast Food]","[Low Carb, Low Calorie, Low Sodium, Low Sugar]",{},1.00,0.000,"Zesty and vibrant, our pizza sauce delivers a ...",...,28g,10,0,80,2,0,1,0,0,0

### Chipotle Data

In [15]:
'''Chipotle categories: ['Beverages' 'Burrito Bowls' 'Extras and Toppings' 'Burritos'
 'Quesadillas' 'Salads' 'Tacos' 'Lifestyle Bowls' 'Tortilla Chips']'''

chip_cat_name = "Burrito Bowls"
display(df_chipotle.loc[df_chipotle['category'] == chip_cat_name])

,item_id,menu_item_id,menu_item_name,restaurant_name,cuisine_type,macronutrient_profile,recipe_items,price,golden_ratio,ai_description,...,serving_size,calories,cholesterol,sodium,total_carbohydrates,dietary_fiber,sugars,protein,potassium,total_fat
2,chipotle_chicken_burrito_bowl,item_66a6aa38b02d47208ed7141199aec1e1,Chicken Burrito Bowl,Chipotle,"[Mexican, Latin American, Tex-Mex]","[High Protein, Low Carb, Low Calorie, Low Sugar]",{},8.50,1.684,"Savor a hearty Chicken Burrito Bowl, featuring...",...,4 oz,190,115,370,1,0,1,32,0,7
13,chipotle_carnitas_burrito_bowl,item_fd10bd13d53e4e8bac079cce1f0e5241,Carnitas Burrito Bowl,Chipotle,"[Mexican, Latin American, Tex-Mex]","[High Protein, Low Carb, Low Calorie, High Sod...",{},8.75,1.421,"Savor the tender, slow-cooked carnitas nestled...",...,4 oz,190,70,540,1,0,0,27,0,8
16,chipotle_sofritas_burrito_bowl,item_fd57cee6af6a41398259e3fdc845250f,Sofritas Burrito Bowl,Chipotle,"[Mexican, Latin American, Tex-Mex]","[Low Carb, High Fat, Low Calorie, High Sodium,...",{},7.50,0.552,Savor the robust flavor of our Sofritas Burrit...,...,4 oz,145,0,555,9,4,5,8,0,10
26,chipotle_plant_based_chorizo_burrito_bowl,item_fd40403bbb2249ee9778ca1b23418fea,Plant Based Chorizo Burrito Bowl,Chipotle,"[Mexican, Latin American, Tex-Mex]","[Low Carb, Low Calorie, High Sodium, Low Sugar]",{},10.50,0.727,Savor the bold flavors of our Plant Based Chor...,...,1 bowl,220,0,690,16,6,1,16,0,8
30,chipotle_barbacoa_burrito_bowl,item_e74b9bbd0a054a80bf7b3a4d09d01213,Barbacoa Burrito Bowl,Chipotle,"[Mexican, Latin American, Tex-Mex]","[High Protein, Low Carb, Low Calorie, High Sod...",{},9.50,1.412,"Savor the tender, shredded barbacoa beef in a ...",...,4 oz,170,60,510,2,0,1,24,0,7
34,chipotle_carne_asada_burrito_bowl,item_648ecf06e0a5471ea24f7ed7a08b0c40,Carne Asada Burrito Bowl,Chipotle,"[Mexican, Latin American, Tex-Mex]","[High Protein, Low Carb, High Fat, Low Calorie...",{},10.50,1.160,Savor the bold flavors of marinated carne asad...,...,1 bowl,250,90,740,1,0,0,29,0,14
38,chipotle_steak_burrito_bowl,item_68f66e0f17e44a94948d5a826296a40d,Steak Burrito Bowl,Chipotle,"[Mexican, Latin American, Tex-Mex]","[High Protein, Low Carb, Low Calorie, Low Sugar]",{},8.50,1.579,"Savor the bold flavors of tender, marinated st...",...,4 oz,190,65,320,2,0,1,30,0,7

In [19]:
# looking at nutrition info for each item to get a better feel for what is in it
# e.g. Chicken Burrito Bowl
print(f"Chicken Burrito Bowl description: {df_chipotle.loc[2, 'ai_description']}")
print(f"Protein: {df_chipotle.loc[2, 'protein']}")
print(f"Calories: {df_chipotle.loc[2, 'calories']}")

# e.g. Carnitas Burrito Bowl
print(f"Carnitas Burrito Bowl description: {df_chipotle.loc[13, 'ai_description']}")
print(f"Protein: {df_chipotle.loc[13, 'protein']}")
print(f"Calories: {df_chipotle.loc[13, 'calories']}")

# e.g. Chicken Quesadilla
print(f"Chicken Quesadilla Protein: {df_chipotle.loc[43, 'protein']}")
print(f"Calories: {df_chipotle.loc[43, 'calories']}")

Chicken Burrito Bowl description: Savor a hearty Chicken Burrito Bowl, featuring tender grilled chicken, zesty cilantro-lime rice, fresh salsas, and protein-packed black beans for a satisfying meal.
Protein: 32
Calories: 190
Carnitas Burrito Bowl description: Savor the tender, slow-cooked carnitas nestled atop a vibrant bed of cilantro-lime rice, black beans, and zesty toppings for a protein-packed delight.
Protein: 27
Calories: 190
Chicken Quesadilla Protein: 58
Calories: 830

Breaking down contents of items in Chipotle:
- Looking at the calorie count for a "Burrito Bowl" and referencing the online Chipotle menu, each item appears to only account for the protein itself. The item does not contain any rice, beans, or other add-ons yet.
- Similarly, "Burritos" are most likely just the protein + tortilla. I assume other categories follow a similar pattern.
- "Lifestyle Bowls" are pre-made and complete bowls.
- sidenote: all "Tacos" have a serving size of 3.

### Some Thoughts After Exploring Data

Issue 1: broader categories like "Kid's Meal" and "Breakfast" in Chick fil A contain items that may be from different categories.
- I'm just going to hard code the differences for this example
    - most items in "Breakfast" category can probably be an "Entree" (with the exception of hash browns)
    - items in the "Kid's Meal" are an entree if they have the word "meal" in the name, "milk" for beverage, and the rest would be sides

Issue 2: when computing combinations in the future, should we try to account for 'realistic' combinations?
- If you order a salad, you would probably want salad dressing to go with it. Blindly assigning meals + sides/add-ons won't always be 'realistic'
- Most likely, you wouldn't want to have salad dressing as an add-on when you ordered a chicken sandwich.

Issue 3: "Build-your-own" restaurants (Chipotle) don't exactly map to the 5 categories
- Possible idea: rather than starting off as an "Entree", each item could instead be labeled as a "Base." A "Base" might require that certain conditions are met before it becomes an "Entree." However, this might be hard to generalize:
    - For example, a Burrito Bowl isn't a bowl yet if it contains only protein.
    - A Burrito is basically still a Taco (tortilla + protein) until you add more toppings.
    - However, a user could possibly be satisfied with a Taco being purely tortilla + protein.

## Assign Meal Categories (Entree, Side, Drink, Dessert, Add-on)
Note: this is hard-coded just to have categories to work with.

### Chick-fil-A

In [20]:
# add a column for meal categories
df_cfa['meal_category'] = 'temp'

# assign meal categories
# note: hard-coded assignment

cfa_entree_categories = ['Classic Chicken', 'Breakfast', 'Cool Wraps', 'Salads', ]
df_cfa.loc[df_cfa['category'].isin(cfa_entree_categories), 'meal_category'] = 'Entree'

df_cfa.loc[df_cfa['category'] == 'Sides', 'meal_category'] = 'Side'

df_cfa.loc[df_cfa['category'] == 'Beverages', 'meal_category'] = 'Drink'

df_cfa.loc[df_cfa['category'] == 'Desserts', 'meal_category'] = 'Dessert'

addon_categories = ['Salad Dressings', 'Sauces']
df_cfa.loc[df_cfa['category'].isin(addon_categories), 'meal_category'] = 'Add-on'

# assigning some categories manually
df_cfa.loc[90, 'meal_category'] = 'Side' # hash brown

kid_mask = df_cfa['category'] == "Kid's Meal"
df_cfa.loc[kid_mask & df_cfa['menu_item_name'].str.contains('Meal', case=False, na=False),'meal_category'] = 'Entree'
df_cfa.loc[kid_mask & df_cfa['menu_item_name'].str.contains('Milk', case=False, na=False),'meal_category'] = 'Drink'
df_cfa.loc[kid_mask & ~df_cfa['menu_item_name'].str.contains('Meal|Milk', case=False, na=False),'meal_category'] = 'Side'

In [21]:
# check that all items got assigned a category
display(df_cfa.loc[df_cfa['meal_category'] == 'temp'])

Empty DataFrame
Columns: [item_id, menu_item_id, menu_item_name, restaurant_name, cuisine_type, macronutrient_profile, recipe_items, price, golden_ratio, ai_description, category, allergen_info, menu_card_image, serving_size, calories, cholesterol, sodium, total_carbohydrates, dietary_fiber, sugars, protein, potassium, total_fat, meal_category]
Index: []

[0 rows x 24 columns]

Sorting the menu items for CFA by category:

In [ ]:
cfa_entrees = df_cfa.loc[df_cfa['meal_category'] == 'Entree'].copy()
cfa_sides = df_cfa.loc[df_cfa['meal_category'] == 'Side'].copy()
cfa_drinks = df_cfa.loc[df_cfa['meal_category'] == 'Drink'].copy()
cfa_desserts = df_cfa.loc[df_cfa['meal_category'] == 'Dessert'].copy()
cfa_addons = df_cfa.loc[df_cfa['meal_category'] == 'Add-on'].copy()

print(f"Count of Entrees: {len(cfa_entrees)}")
print(f"Count of Sides: {len(cfa_sides)}")
print(f"Count of Drinks: {len(cfa_drinks)}")
print(f"Count of Desserts: {len(cfa_desserts)}")
print(f"Count of Add-Ons: {len(cfa_addons)}")

Count of Entrees: 76
Count of Sides: 19
Count of Drinks: 43
Count of Desserts: 24
Count of Add-Ons: 15

### Taco Bell

Items of concern:
- Cheesy roll up in 'Specialties': not sufficient to be an entree
- Cinnabon Delights (2, 4, and 12 pc): I will put in "Dessert" for now

In [23]:
# add a column for meal categories
df_tb['meal_category'] = 'temp'

tb_entree_categories = ['Burritos', 'Tacos', 'Breakfast', 'Cantina Chicken','Chalupas', 'Nachos', 'Specialties']
df_tb.loc[df_tb['category'].isin(tb_entree_categories), 'meal_category'] = 'Entree'

df_tb.loc[df_tb['category'] == 'Sides', 'meal_category'] = 'Side'

df_tb.loc[df_tb['category'] == 'Beverages', 'meal_category'] = 'Drink'

df_tb.loc[df_tb['category'] == "Condiments & Sauces", 'meal_category'] = 'Add-on'

# manual assignments
df_tb.loc[91, 'meal_category'] = 'Side'     # hash brown
df_tb.loc[194, 'meal_category'] = 'Side'    # cheesy roll up
df_tb.loc[df_tb['menu_item_name'] == "Cinnabon Delights", 'meal_category'] = 'Dessert'

In [24]:
# check that all items got assigned a category
display(df_tb.loc[df_tb['meal_category'] == 'temp'])

Empty DataFrame
Columns: [item_id, menu_item_id, menu_item_name, restaurant_name, cuisine_type, macronutrient_profile, recipe_items, price, golden_ratio, ai_description, category, allergen_info, menu_card_image, serving_size, calories, cholesterol, sodium, total_carbohydrates, dietary_fiber, sugars, protein, potassium, total_fat, meal_category]
Index: []

[0 rows x 24 columns]

Sorting the menu items for Taco Bell by category:

In [30]:
tb_entrees = df_tb.loc[df_tb['meal_category'] == 'Entree'].copy()
tb_sides = df_tb.loc[df_tb['meal_category'] == 'Side'].copy()
tb_drinks = df_tb.loc[df_tb['meal_category'] == 'Drink'].copy()
tb_desserts = df_tb.loc[df_tb['meal_category'] == 'Dessert'].copy()
tb_addons = df_tb.loc[df_tb['meal_category'] == 'Add-on'].copy()

print(f"Count of Entrees: {len(tb_entrees)}")
print(f"Count of Sides: {len(tb_sides)}")
print(f"Count of Drinks: {len(tb_drinks)}")
print(f"Count of Desserts: {len(tb_desserts)}")
print(f"Count of Add-Ons: {len(tb_addons)}")

Count of Entrees: 75
Count of Sides: 16
Count of Drinks: 87
Count of Desserts: 3
Count of Add-Ons: 24

### Chipotle: TBD

## Meal Combination Exploration

Information to calculate when storing meals:
- calories
- protein
- price

### Chick-fil-A

Naive approach: precompute all meals

In [38]:
import itertools

In [ ]:
# forcing the combo to at least have Entree, Side, and Drink
def compute_all_cfa_combos(addons=False, desssert=False):
    categories = [cfa_entrees, cfa_sides, cfa_drinks]
    
    if addons:
        categories.append(cfa_addons)
    
    if desssert:
        categories.append(cfa_desserts)
    
    combinations = itertools.product(*categories)
    return combinations     # returns an iterator object

In [ ]:
iter_cfa_combo_basic = compute_all_cfa_combos()
list_cfa_combo_basic = list(iter_cfa_combo_basic)
print(f"Number of total combinations for Entree + Side + Drink combo: {len(list_cfa_combo_basic)}")

iter_cfa_combo_extra = compute_all_cfa_combos(addons=True, desssert=True)
list_cfa_combo_extra = list(iter_cfa_combo_extra)
print(f"Number of total combinations for Entree, Side, Drink, Dessert and Add-On combo: {len(list_cfa_combo_extra)}")

Number of total combinations for Entree + Side + Drink combo: 62092
Number of total combinations for Entree, Side, Drink, Dessert and Add-On combo: 22353120

## Meal Combination Storage and Computation Ideas

1. Knapsack Approach
    - 0/1 Knapsack problem: 
            
        _"Given two arrays, `profit[]` and `weight[]`, where each element represents the profit and weight of an item respectively, also given an integer `W` representing the maximum capacity of the knapsack (the total weight it can hold)._
        
        _Put the items into the knapsack such that the sum of profits associated with them is the maximum possible, without exceeding the capacity W."_
        
        (https://www.geeksforgeeks.org/dsa/0-1-knapsack-problem-dp-10/)
    - Concern:
        - Knapsack tries to maximize a single value from a pool of items and returns a best solution. We want to hit targets (protein, calories, price) without losing structure to meals (maintain rules with categories).
        - We want to have multiple top picks and rank results. We would have to adjust knapsack to give best k results.
        - Overall, knapsack on its own may not be sufficient for meal building. However, it may have a use when trying to maximize leftover calories.

2. Meal Precomputation
    - Storing every single meal combination is inefficient
    - Recomputing every single meal after a user request is also inefficient
    - Another note: allowing for multiple entrees (maybe max 2-3) can allow for goals to be hit quicker. 
    - Architecture idea:
        1. Precompute entree combinations. Store UID, item IDs, protein total, calorie total, price total
        2. Filter dynamically after user interaction. Use boolen masking/vectorization (quick) to filter for acceptable protein, price, and calorie ranges.
        3. Add on optional sides or drinks (add-ons can come in later).
        4. Apply scoring algorithm.
    - Expansion: add some sort of caching mechanism for common presets

    - Edits to this approach: _all_ entree combinations may also explode as system grows. We can possibly filter down "unreasonable" combinations to reduce storage.

### Entree Precomputation
It is useful to adjust the storage of the entrees before calculating their combinations.

In [41]:
cfa_entrees_dict = cfa_entrees[["menu_item_id", "menu_item_name", "price", "calories", "protein"]].to_dict("records")

In [42]:
# these are based on the filters within Eatery
MAX_PRICE = 100.0
MAX_CALORIES = 3000   
MAX_PROTEIN = 150


def calculate_entree_combos(entrees, max_count=2):
    entree_combos = []
    combo_id = 1    # change id numbering later, maybe

    for k in range(1, max_count+1):
        for combo in itertools.combinations_with_replacement(entrees, k):
            # calculate totals
            total_price = sum(item['price'] for item in combo)
            total_calories = sum(item['calories'] for item in combo)
            total_protein = sum(item['protein'] for item in combo)


            if total_price > MAX_PRICE:
                continue
            if total_calories > MAX_CALORIES:
                continue
            if total_price > MAX_PRICE:
                continue

            entree_combos.append({
                "combo_id": combo_id,
                "entree_ids": tuple(item['menu_item_id'] for item in combo),
                "entree_names": tuple(item['menu_item_name'] for item in combo),
                "n_entrees": k,
                "price": total_price,
                "calories": total_calories,
                "protein": total_protein
            })

            combo_id += 1
    
    return pd.DataFrame(entree_combos)

In [36]:
def display_entree_combo(row_entry):
    print(f"Combo ID is {row_entry['combo_id']}")
    print(f"There are {row_entry['n_entrees']} entrees in this combo: {row_entry['entree_names']}")
    print(f"Total price is: {row_entry['price']}")
    print(f"Total calories are: {row_entry['calories']}")
    print(f"Total protein is: {row_entry['protein']}")

Testing the computation on Chick-fil-A:

In [43]:
cfa_entree_combos = calculate_entree_combos(cfa_entrees_dict)

In [45]:
display(cfa_entree_combos)

,combo_id,entree_ids,entree_names,n_entrees,price,calories,protein
0,1,"(item_818528ff980240e39250845e28b061f7,)","(Chick-n-Strips,)",1,4.29,200,19
1,2,"(item_44dbe341c1dd40f095ad04f1bced08e9,)","(Chicken Nuggets,)",1,3.49,130,13
2,3,"(item_44dbe341c1dd40f095ad04f1bced08e9,)","(Chicken Nuggets,)",1,4.99,250,27
3,4,"(item_44dbe341c1dd40f095ad04f1bced08e9,)","(Chicken Nuggets,)",1,14.99,970,103
4,5,"(item_818528ff980240e39250845e28b061f7,)","(Chick-n-Strips,)",1,6.99,410,39
...,...,...,...,...,...,...,...
2997,2998,"(item_e89cf65042ea4351b512ff6e2ea37e5e, item_e...","(Spicy Southwest Salad, Spicy Southwest Salad)",2,21.98,1080,80
2998,2999,"(item_e89cf65042ea4351b512ff6e2ea37e5e, item_e...","(Spicy Southwest Salad, Spicy Southwest Salad)",2,21.98,1250,84
2999,3000,"(item_e89cf65042ea4351b512ff6e2ea37e5e, item_e...","(Spicy Southwest Salad, Spicy Southwest Salad)",2,21.98,960,78
3000,3001,"(item_e89cf65042ea4351b512ff6e2ea37e5e, item_e...","(Spicy Southwest Salad, Spicy Southwest Salad)",2,21.98,1130,82
3001,3002,"(item_e89cf65042ea4351b512ff6e2ea37e5e, item_e...","(Spicy Southwest Salad, Spicy Southwest Salad)",2,21.98,1300,86

Display a few combinations from Chick-fil-A:

In [52]:
display_entree_combo(cfa_entree_combos.loc[0])
display_entree_combo(cfa_entree_combos.loc[1000])
display_entree_combo(cfa_entree_combos.loc[2900])

Combo ID is 1
There are 1 entrees in this combo: ('Chick-n-Strips',)
Total price is: 4.29
Total calories are: 200
Total protein is: 19
Combo ID is 1001
There are 2 entrees in this combo: ('Smokehouse BBQ Bacon Sandwich', 'Hash Brown Scramble Burrito')
Total price is: 11.98
Total calories are: 1300
Total protein is: 71
Combo ID is 2901
There are 2 entrees in this combo: ('Market Salad', 'Spicy Southwest Salad')
Total price is: 20.98
Total calories are: 770
Total protein is: 62

Some notes:
- This is still not accounting for variations of an item. For example, this blind combination will combine a 4pc nugget with a 8pc nugget.