# Meal Combination Sandbox
_Disclaimer: This code is not final, but just an exploration. The storage and data structures used are simply for the purpose of this notebook._

## Load Data

In [1]:
import json
import pandas as pd

with open('../restaurants.menu_item_variations.json', 'r') as file:
    item_list = json.load(file)
file.close()

## Select all Items for Specific Restaurants: Chick-fil-A, Taco Bell, and Chipotle

In [2]:
chick_fil_a_items = []
tacobell_items = []
chipotle_items = []

for item in item_list:
    if item.get("restaurant_name") == "Chick-fil-A":
        chick_fil_a_items.append(item)

    elif item.get("restaurant_name") == "Taco Bell":
        tacobell_items.append(item)
    
    elif item.get("restaurant_name") == "Chipotle":
        chipotle_items.append(item)

print(f"Number of Chick-fil-A items: {len(chick_fil_a_items)}")
print(f"Number of Taco Bell items: {len(tacobell_items)}")
print(f"Number of Chipotle items: {len(chipotle_items)}")

# making dataframes just to visualize easier
df_cfa = pd.DataFrame(chick_fil_a_items)
df_tb = pd.DataFrame(tacobell_items)
df_chipotle = pd.DataFrame(chipotle_items)

df_cfa.reset_index(inplace=True)
df_tb.reset_index(inplace=True)
df_chipotle.reset_index(inplace=True)

Number of Chick-fil-A items: 177
Number of Taco Bell items: 205
Number of Chipotle items: 99

In [3]:
# extract nutrition information as columns
def extract_nutrition(df):
    nutrition_df = df["nutrition_info"].apply(pd.Series)
    df = pd.concat([df.drop(columns=["nutrition_info"]), nutrition_df], axis=1)
    return df

df_cfa = extract_nutrition(df_cfa)
df_tb = extract_nutrition(df_tb)
df_chipotle = extract_nutrition(df_chipotle)

### Visualization

In [4]:
# Chick fil A items
df_cfa.head()

,index,item_id,menu_item_id,menu_item_name,restaurant_name,cuisine_type,macronutrient_profile,recipe_items,price,golden_ratio,...,serving_size,calories,cholesterol,sodium,total_carbohydrates,dietary_fiber,sugars,protein,potassium,total_fat
0,0,chick_fil_a_chick_n_strips,item_818528ff980240e39250845e28b061f7,Chick-n-Strips,Chick-fil-A,"[American, Fast Food, Southern]","[High Protein, Low Carb, Low Calorie, High Sod...",{},4.29,0.950,...,2 strips,200,50,580,11,0,1,19,0,9
1,1,chick_fil_a_chicken_nuggets,item_44dbe341c1dd40f095ad04f1bced08e9,Chicken Nuggets,Chick-fil-A,"[American, Fast Food, Southern]","[Low Carb, Low Calorie, High Sodium, Low Sugar]",{},3.49,1.000,...,4 nuggets,130,40,610,5,0,0,13,0,6
2,2,chick_fil_a_chicken_nuggets,item_44dbe341c1dd40f095ad04f1bced08e9,Chicken Nuggets,Chick-fil-A,"[American, Fast Food, Southern]","[High Protein, Low Carb, Low Calorie, High Sod...",{},4.99,1.080,...,8 nuggets,250,85,1210,11,0,1,27,0,11
3,3,chick_fil_a_chicken_nuggets,item_44dbe341c1dd40f095ad04f1bced08e9,Chicken Nuggets,Chick-fil-A,"[American, Fast Food, Southern]","[High Protein, Low Carb, High Calorie, High So...",{},14.99,1.062,...,30 nuggets,970,285,3660,35,4,1,103,0,46
4,4,chick_fil_a_chick_n_strips,item_818528ff980240e39250845e28b061f7,Chick-n-Strips,Chick-fil-A,"[American, Fast Food, Southern]","[High Protein, High Sodium, Low Sugar]",{},6.99,0.951,...,4 strips,410,100,1150,22,0,2,39,0,19

In [5]:
# Taco Bell items
df_tb.head()

,index,item_id,menu_item_id,menu_item_name,restaurant_name,cuisine_type,macronutrient_profile,recipe_items,price,golden_ratio,...,serving_size,calories,cholesterol,sodium,total_carbohydrates,dietary_fiber,sugars,protein,potassium,total_fat
0,0,taco_bell_bean_burrito,item_bc872feac0cd4c038de6a4bc27b91eef,Bean Burrito,Taco Bell,"[Mexican, American, Fast Food]","[High Carb, Low Calorie, High Sodium, Low Sugar]",{},1.29,0.371,...,1 burrito,350,5,1000,54,11,3,13,0,9
1,1,taco_bell_beefy_5_layer_burrito,item_68a8b72cef0e4ac9acf2b3cb8445ef23,Beefy 5-Layer Burrito,Taco Bell,"[Mexican, American, Fast Food]","[High Sodium, Low Sugar]",{},2.99,0.367,...,1 burrito,490,30,1250,63,9,5,18,0,18
2,2,taco_bell_burrito_supreme_chicken,item_d8bbc465a2ff443f99500235a73971c9,Burrito Supreme - Chicken,Taco Bell,"[Mexican, American, Fast Food]","[High Sodium, Low Sugar]",{},3.99,0.514,...,1 burrito,370,35,1110,49,8,4,19,0,11
3,3,taco_bell_chicken_enchilada_burrito,item_2185ad40296c41209c67ba5496401929,Chicken Enchilada Burrito,Taco Bell,"[Mexican, American, Fast Food]","[High Sodium, Low Sugar]",{},3.99,0.500,...,1 burrito,380,40,1150,49,3,3,19,0,12
4,4,taco_bell_coffee_with_creamer,item_1aaeafaf9be14badb5ce82fcd2e2aaaa,Coffee with Creamer,Taco Bell,"[Mexican, American, Fast Food]","[Low Carb, Low Calorie, Low Sodium, Low Sugar]",{},2.49,0.667,...,1 coffee,30,0,0,3,0,3,2,0,2

In [6]:
# chipotle items
df_chipotle.head()

,index,item_id,menu_item_id,menu_item_name,restaurant_name,cuisine_type,macronutrient_profile,recipe_items,price,golden_ratio,...,serving_size,calories,cholesterol,sodium,total_carbohydrates,dietary_fiber,sugars,protein,potassium,total_fat
0,0,chipotle_izze_sparkling_blackberry_soda,item_09007bf4a7904846a73f8438b299f460,Izze Sparkling Blackberry Soda,Chipotle,"[Mexican, Latin American, Tex-Mex]","[High Carb, Low Calorie, Low Sodium, Low Sugar]",{},2.50,0.000,...,1 bottle,170,0,35,41,0,39,0,0,0
1,1,chipotle_tractor_hibiscus_lemonade,item_86b8d873b6f840e4822df75ba6baac51,Tractor Hibiscus Lemonade,Chipotle,"[Mexican, Latin American, Tex-Mex]","[High Carb, Low Calorie, Low Sodium, Low Sugar]",{},3.50,0.000,...,22 oz,150,0,0,36,0,35,0,0,0
2,2,chipotle_chicken_burrito_bowl,item_66a6aa38b02d47208ed7141199aec1e1,Chicken Burrito Bowl,Chipotle,"[Mexican, Latin American, Tex-Mex]","[High Protein, Low Carb, Low Calorie, Low Sugar]",{},8.50,1.684,...,4 oz,190,115,370,1,0,1,32,0,7
3,3,chipotle_black_beans,item_1c084543ac7b4259873ac1bf141574e9,Black Beans,Chipotle,"[Mexican, Latin American, Tex-Mex]","[High Carb, Low Calorie, Low Sugar]",{},2.50,0.583,...,4 oz,120,0,250,23,11,0,7,0,1
4,4,chipotle_carnitas_burrito,item_7d30d25697de4ecdaab8169d37d5e74a,Carnitas Burrito,Chipotle,"[Mexican, Latin American, Tex-Mex]","[High Protein, High Sodium, Low Sugar, Balanced]",{},9.75,0.708,...,4 oz,480,70,1210,45,2,0,34,0,17

### Categories

Display all categories for Chick-fil-A, Taco Bell, and Chipotle.

In [7]:
cfa_categories = df_cfa['category'].unique()
tb_categories = df_tb['category'].unique()
chip_categories = df_chipotle['category'].unique()

print(f"Chick fil A categories: {cfa_categories}")
print(f"Taco Bell categories: {tb_categories}")
print(f"Chipotle categories: {chip_categories}")

Chick fil A categories: ['Classic Chicken' 'Beverages' 'Breakfast' 'Desserts' "Kid's Meal"
 'Salad Dressings' 'Cool Wraps' 'Sauces' 'Sides' 'Salads']
Taco Bell categories: ['Burritos' 'Beverages' 'Tacos' 'Breakfast' 'Cantina Chicken'
 'Condiments & Sauces' 'Chalupas' 'Nachos' 'Sides' 'Specialties']
Chipotle categories: ['Beverages' 'Burrito Bowls' 'Extras and Toppings' 'Burritos'
 'Quesadillas' 'Salads' 'Tacos' 'Lifestyle Bowls' 'Tortilla Chips']

## Exploring Data

Checking the content of some categories to distinguish what meal component they may be. (Feel free to explore yourself)

### Chick-fil-A Data

In [8]:
'''Chick fil A categories: ['Classic Chicken' 'Beverages' 'Breakfast' 'Desserts' "Kid's Meal"
 'Salad Dressings' 'Cool Wraps' 'Sauces' 'Sides' 'Salads']'''

cfa_cat_name = "Breakfast"
display(df_cfa.loc[df_cfa['category'] == cfa_cat_name])

,index,item_id,menu_item_id,menu_item_name,restaurant_name,cuisine_type,macronutrient_profile,recipe_items,price,golden_ratio,...,serving_size,calories,cholesterol,sodium,total_carbohydrates,dietary_fiber,sugars,protein,potassium,total_fat
53,53,chick_fil_a_hash_brown_scramble_burrito,item_57b571666c3e48fc8f253bb0e65e1315,Hash Brown Scramble Burrito,Chick-fil-A,"[American, Fast Food, Southern]","[High Protein, High Fat, High Calorie, High So...",{},4.99,0.486,...,1 burrito,700,415,1750,51,3,2,34,0,40
55,55,chick_fil_a_bacon_egg_cheese_biscuit,item_4113c01c405f4ec5ac415e8ffa67c34d,"Bacon, Egg & Cheese Biscuit",Chick-fil-A,"[American, Fast Food, Southern]","[High Sodium, Low Sugar]",{},3.99,0.357,...,1 biscuit,420,180,1290,38,2,4,15,0,23
57,57,chick_fil_a_chicken_biscuit,item_8c359b035e514162add9db3dfcca12c7,Chicken Biscuit,Chick-fil-A,"[American, Fast Food, Southern]","[High Sodium, Low Sugar]",{},3.99,0.413,...,1 biscuit,460,45,1510,45,2,6,19,0,23
58,58,chick_fil_a_yogurt_parfait_w_cookie_cumbs,item_696737d778b34b2caf288baebc324099,Yogurt Parfait w/ Cookie Cumbs,Chick-fil-A,"[American, Fast Food, Southern]","[Low Calorie, Low Sodium, Low Sugar]",{},4.99,0.480,...,1 parfait,250,15,85,33,1,26,12,0,8
60,60,chick_fil_a_egg_cheese_english_muffin,item_07042d87afd04700973507580773663d,Egg & Cheese English Muffin,Chick-fil-A,"[American, Fast Food, Southern]","[Low Calorie, High Sodium, Low Sugar]",{},3.99,0.533,...,1 sandwich,300,180,800,29,1,2,16,0,14
61,61,chick_fil_a_hash_brown_scramble_burrito,item_57b571666c3e48fc8f253bb0e65e1315,Hash Brown Scramble Burrito,Chick-fil-A,"[American, Fast Food, Southern]","[High Protein, High Fat, High Calorie, High So...",{},4.99,0.394,...,1 burrito,710,395,1440,46,3,1,28,0,46
62,62,chick_fil_a_yogurt_parfait_with_harvest_nut_gr...,item_440d8ca23c2b4ecfa16ddc71e9c0d1aa,Yogurt Parfait with Harvest Nut Granola,Chick-fil-A,"[American, Fast Food, Southern]","[Low Calorie, Low Sodium, Low Sugar]",{},4.99,0.464,...,1 parfait,280,15,85,37,1,27,13,0,8
65,65,chick_fil_a_egg_white_grill,item_403c6de25b2845a0b3804449be646e8a,Egg White Grill,Chick-fil-A,"[American, Fast Food, Southern]","[High Protein, Low Calorie, High Sodium, Low S...",{},4.99,0.862,...,1 sandwich,290,60,970,29,1,2,25,0,8
66,66,chick_fil_a_hash_brown_scramble_bowl,item_cd3d9826a6cd40e58b2bd0eaf8a084df,Hash Brown Scramble Bowl,Chick-fil-A,"[American, Fast Food, Southern]","[High Protein, Low Carb, High Fat, High Sodium...",{},6.99,0.617,...,1 bowl,470,415,1340,19,2,2,29,0,30
67,67,chick_fil_a_chicken_egg_cheese_biscuit,item_be2be90336df444faa0fc92fe6768944,"Chicken, Egg & Cheese Biscuit",Chick-fil-A,"[American, Fast Food, Southern]","[High Protein, High Sodium, Low Sugar]",{},4.99,0.491,...,206g,530,215,1830,45,2,7,26,0,27
68,68,chick_fil_a_egg_cheese_english_muffin,item_07042d87afd04700973507580773663d,Egg & Cheese English Muffin,Chick-fil-A,"[American, Fast Food, Southern]","[High Fat, High Sodium, Low Sugar]",{},4.99,0.462,...,1 sandwich,520,210,1060,30,1,2,24,0,34
70,70,chick_fil_a_hash_brown_scramble_bowl,item_cd3d9826a6cd40e58b2bd0eaf8a084df,Hash Brown Scramble Bowl,Chick-fil-A,"[American, Fast Food, Southern]","[Low Carb, High Fat, High Sodium, Low Sugar]",{},5.99,0.479,...,1 bowl,480,395,1010,15,2,1,23,0,37
71,71,chick_fil_a_sausage_egg_and_cheese_biscuit,item_b10274268e6548108b9d1b1058b026e3,Sausage Egg and Cheese Biscuit,Chick-fil-A,"[American, Fast Food, Southern]","[High Fat, High Sodium, Low Sugar]",{},3.99,0.365,...,1 biscuit,630,210,1540,38,2,4,23,0,43
74,74,chick_fil_a_hot_buttered_biscuit,item_80103285c8bc4f86881e8e077169afe1,Hot Buttered Biscuit,Chick-fil-A,"[American, Fast Food, Southern]","[Low Protein, Low Calorie, High Sodium, Low Su...",{},2.49,0.138,...,1 biscuit,290,0,760,37,2,4,4,0,15
76,76,chick_fil_a_chick_n_minis,item_66c20fcaff8644dfa4e339fe9772a52c,Chick-n-Minis,Chick-fil-A,"[American, Fast Food, Southern]","[Low Calorie, High Sodium, Low Sugar]",{},3.99,0.571,...,94g,280,40,650,30,1,5,16,0,10
79,79,chick_fil_a_chick_n_minis,item_66c20fcaff8644dfa4e339fe9772a52c,Chick-n-Minis,Chick-fil-A,"[American, Fast Food, Southern]","[High Protein, High Calorie, High Sodium, Low ...",{},14.99,0.552,...,10 sliders,870,130,2150,92,5,14,48,0,35
80,80,chick_fil_a_hash_brown_scramble_bowl,item_cd3d9826a6cd40e58b2bd0eaf8a084df,Hash Brown Scramble Bowl,Chick-fil-A,"[American, Fast Food, Southern]","[High Protein, Low Carb, High Fat, High Sodium...",{},6.99,0.732,...,1 bowl,410,415,1190,15,2,2,30,0,26
81,81,chick_fil_a_hash_brown_scramble_burrito,item_57b571666c3e48fc8f253bb0e65e1315,Hash Brown Scramble Burrito,Chick-fil-A,"[American, Fast Food, Southern]",[],{},4.99,0.000,...,1 serving,0,0,0,0,0,0,0,0,0
82,82,chick_fil_a_hash_brown_scramble_burrito,item_57b571666c3e48fc8f253bb0e65e1315,Hash Brown Scramble Burrito,Chick-fil-A,"[American, Fast Food, Southern]","[High Protein, High Sodium, Low Sugar]",{},6.99,0.538,...,1 burrito,650,415,1620,46,3,2,35,0,36
86,86,chick_fil_a_chick_n_minis,item_66c20fcaff8644dfa4e339fe9772a52c,Chick-n-Minis,Chick-fil-A,"[American, Fast Food, Southern]","[High Sodium, Low Sugar, Balanced]",{},4.29,0.568,...,126g,370,50,870,41,2,7,21,0,14
87,87,chick_fil_a_chicken_egg_cheese_muffin,item_a7c5d7c2c4d34bb1b9d1d6172662fd79,"Chicken, Egg, & Cheese Muffin",Chick-fil-A,"[American, Fast Food, Southern]","[High Protein, High Sodium, Low Sugar]",{},4.99,0.643,...,190g,420,215,1350,37,1,4,27,0,19
88,88,chick_fil_a_english_muffin,item_563cef2dab0c4a04a3b41560ab98967a,English Muffin,Chick-fil-A,"[American, Fast Food, Southern]","[High Carb, Low Calorie, Low Sodium, Low Sugar]",{},2.49,0.357,...,1 English muffin,140,0,220,29,1,1,5,0,2
89,89,chick_fil_a_hash_brown_scramble_bowl,item_cd3d9826a6cd40e58b2bd0eaf8a084df,Hash Brown Scramble Bowl,Chick-fil-A,"[American, Fast Food, Southern]","[High Protein, Low Carb, High Fat, High Sodium...",{},6.99,0.609,...,1 bowl,460,405,1360,19,2,2,28,0,30
90,90,chick_fil_a_hash_browns,item_0589871236764832a5e65428d0048eac,Hash Browns,Chick-fil-A,"[American, Fast Food, Southern]","[Low Protein, High Fat, Low Calorie, Low Sugar]",{},2.99,0.111,...,77g,270,0,440,23,3,0,3,0,18
92,92,chick_fil_a_spicy_chicken_biscuit,item_b0056ed759974de0ae0ef93c4bc18032,Spicy Chicken Biscuit,Chick-fil-A,"[American, Fast Food, Southern]","[High Sodium, Low Sugar]",{},4.99,0.395,...,145g,430,30,1300,43,2,5,17,0,21

### Taco Bell Data

In [64]:
'''Taco Bell categories: ['Burritos' 'Beverages' 'Tacos' 'Breakfast' 'Cantina Chicken'
 'Condiments & Sauces' 'Chalupas' 'Nachos' 'Sides' 'Specialties']'''

tb_cat_name = "Condiments & Sauces"
display(df_tb.loc[df_tb['category'] == tb_cat_name])

,index,item_id,menu_item_id,menu_item_name,restaurant_name,cuisine_type,macronutrient_profile,recipe_items,price,golden_ratio,...,calories,cholesterol,sodium,total_carbohydrates,dietary_fiber,sugars,protein,potassium,total_fat,meal_category
129,129,taco_bell_mild_sauce,item_b1a34e10fe684507b6e87b1a29dc95e6,Mild Sauce,Taco Bell,"[Mexican, American, Fast Food]",[],{},1.00,0.000,...,0,0,30,0,0,0,0,0,0,Add-on
131,131,taco_bell_breakfast_salsa,item_ee95089c94294d589ac6839024ae4ecb,Breakfast Salsa,Taco Bell,"[Mexican, American, Fast Food]","[Low Carb, Low Calorie, Low Sodium, Low Sugar]",{},1.00,0.000,...,0,0,50,1,0,0,0,0,0,Add-on
132,132,taco_bell_nugget_dipping_sauce,item_2ebeb298d6cc4d98b88fc6ad8a9db7dc,Nugget Dipping Sauce,Taco Bell,"[Mexican, American, Fast Food]","[Low Carb, High Fat, Low Calorie, Low Sodium, ...",{},1.00,0.000,...,200,5,160,8,0,7,0,0,19,Add-on
133,133,taco_bell_pepper_jack_sauce,item_b076a600c6584b8f9234c6f9a40d9780,Pepper Jack Sauce,Taco Bell,"[Mexican, American, Fast Food]","[Low Carb, High Fat, Low Calorie, Low Sodium, ...",{},1.00,0.000,...,70,5,50,1,0,0,0,0,7,Add-on
134,134,taco_bell_premium_guacamole_dip,item_57756f900d064b1c8acc474e942926d8,Premium Guacamole Dip,Taco Bell,"[Mexican, American, Fast Food]","[Low Carb, High Fat, Low Calorie, Low Sodium, ...",{},1.49,0.143,...,70,0,210,3,2,0,1,0,6,Add-on
136,136,taco_bell_creamy_jalapeno_sauce,item_21f4680809bf4371bb5548cc92c355ad,Creamy Jalapeno Sauce,Taco Bell,"[Mexican, American, Fast Food]","[Low Carb, High Fat, Low Calorie, Low Sodium, ...",{},1.00,0.000,...,70,0,50,1,0,1,0,0,7,Add-on
137,137,taco_bell_red_sauce,item_25816abada984710ad3583e845c86afb,Red Sauce,Taco Bell,"[Mexican, American, Fast Food]","[Low Carb, Low Calorie, Low Sodium, Low Sugar]",{},1.00,0.000,...,10,0,170,2,0,0,0,0,0,Add-on
138,138,taco_bell_reduced_fat_sour_cream_dip,item_550942d163114ef9b28c00a7059833cf,Reduced-Fat Sour Cream Dip,Taco Bell,"[Mexican, American, Fast Food]","[Low Carb, High Fat, Low Calorie, Low Sodium, ...",{},1.49,0.167,...,60,10,45,4,0,2,1,0,4,Add-on
139,139,taco_bell_salsa,item_de49ee06b6754e869f52d8121a22a6c8,Salsa,Taco Bell,"[Mexican, American, Fast Food]","[Low Carb, Low Calorie, Low Sodium, Low Sugar]",{},1.00,0.000,...,5,0,80,1,0,1,0,0,0,Add-on
142,142,taco_bell_hot_sauce,item_d485a1a5657a47d9b7d8b9be477d9a0b,Hot Sauce,Taco Bell,"[Mexican, American, Fast Food]",[],{},1.00,0.000,...,0,0,45,0,0,0,0,0,0,Add-on
143,143,taco_bell_nugget_dipping_sauce,item_2ebeb298d6cc4d98b88fc6ad8a9db7dc,Nugget Dipping Sauce,Taco Bell,"[Mexican, American, Fast Food]","[Low Carb, High Fat, Low Calorie, Low Sodium, ...",{},1.00,0.000,...,210,10,210,5,1,4,0,60,21,Add-on
145,145,taco_bell_diablo_sauce,item_89e18e63e25242a78c7bbb6a8670e02f,Diablo Sauce,Taco Bell,"[Mexican, American, Fast Food]",[],{},1.00,0.000,...,0,0,30,0,0,0,0,0,0,Add-on
146,146,taco_bell_salsa_verde,item_b53e9d3fe55d416d84f42e910db685ce,Salsa Verde,Taco Bell,"[Mexican, American, Fast Food]","[Low Carb, Low Calorie, Low Sodium, Low Sugar]",{},1.00,0.000,...,5,0,55,1,0,0,0,0,0,Add-on
149,149,taco_bell_cilantro_dressing,item_f65327221b254042b242e76fd96045e4,Cilantro Dressing,Taco Bell,"[Mexican, American, Fast Food]","[Low Carb, High Fat, Low Calorie, Low Sodium, ...",{},1.00,0.000,...,90,10,210,2,0,0,0,0,9,Add-on
150,150,taco_bell_green_tomatillo_sauce,item_5a84f49c2b2048009b73e4875fc13443,Green Tomatillo Sauce,Taco Bell,"[Mexican, American, Fast Food]","[Low Carb, Low Calorie, Low Sodium, Low Sugar]",{},1.00,0.000,...,10,0,170,2,0,1,0,0,0,Add-on
151,151,taco_bell_guacamole,item_3673039a1d96483fa6bafd1219f8a2a5,Guacamole,Taco Bell,"[Mexican, American, Fast Food]","[Low Carb, High Fat, Low Calorie, Low Sodium, ...",{},1.49,0.000,...,35,0,105,2,1,0,0,0,3,Add-on
152,152,taco_bell_nugget_dipping_sauce,item_2ebeb298d6cc4d98b88fc6ad8a9db7dc,Nugget Dipping Sauce,Taco Bell,"[Mexican, American, Fast Food]","[Low Carb, High Fat, Low Calorie, Low Sodium, ...",{},1.00,0.000,...,210,15,200,3,0,1,0,2,22,Add-on
156,156,taco_bell_pico_de_gallo,item_224b6c9b78004f0195c008c797cd9ae9,Pico de Gallo,Taco Bell,"[Mexican, American, Fast Food]","[Low Carb, Low Calorie, Low Sodium, Low Sugar]",{},1.29,0.000,...,5,0,35,1,0,1,0,0,0,Add-on
157,157,taco_bell_salsa_dip,item_845c7684c2ab4c758dad9635386cb1f3,Salsa Dip,Taco Bell,"[Mexican, American, Fast Food]","[Low Carb, Low Calorie, Low Sodium, Low Sugar]",{},1.49,0.000,...,10,0,220,2,0,1,0,0,0,Add-on
158,158,taco_bell_reduced_fat_sour_cream,item_10f9e73cfcab46b0b6a6a8c349dafbce,Reduced Fat Sour Cream,Taco Bell,"[Mexican, American, Fast Food]","[Low Carb, High Fat, Low Calorie, Low Sodium, ...",{},1.00,0.333,...,30,5,20,2,0,1,1,0,2,Add-on
161,161,taco_bell_fire_sauce,item_f0d2b6bd85e644c180f213f736f88dab,Fire Sauce,Taco Bell,"[Mexican, American, Fast Food]",[],{},1.00,0.000,...,0,0,55,0,0,0,0,0,0,Add-on
167,167,taco_bell_spicy_ranch_dip,item_7e8438a5632c4accaf0a34184bf3de7b,Spicy Ranch Dip,Taco Bell,"[Mexican, American, Fast Food]","[Low Carb, High Fat, Low Calorie, Low Sugar, K...",{},1.49,0.043,...,230,20,280,2,0,2,1,0,24,Add-on
168,168,taco_bell_nacho_cheese_dip,item_90e6b83a5351467a89d238d4761ac5a2,Nacho Cheese Dip,Taco Bell,"[Mexican, American, Fast Food]","[Low Carb, High Fat, Low Calorie, Low Sugar, K...",{},1.49,0.600,...,150,35,250,2,1,0,9,0,12,Add-on
169,169,taco_bell_pizza_sauce,item_173cbf2ddce147b180cfea34697b6cb1,Pizza Sauce,Taco Bell,"[Mexican, American, Fast Food]","[Low Carb, Low Calorie, Low Sodium, Low Sugar]",{},1.00,0.000,...,10,0,80,2,0,1,0,0,0,Add-on

### Chipotle Data

In [10]:
'''Chipotle categories: ['Beverages' 'Burrito Bowls' 'Extras and Toppings' 'Burritos'
 'Quesadillas' 'Salads' 'Tacos' 'Lifestyle Bowls' 'Tortilla Chips']'''

chip_cat_name = "Burrito Bowls"
display(df_chipotle.loc[df_chipotle['category'] == chip_cat_name])

,index,item_id,menu_item_id,menu_item_name,restaurant_name,cuisine_type,macronutrient_profile,recipe_items,price,golden_ratio,...,serving_size,calories,cholesterol,sodium,total_carbohydrates,dietary_fiber,sugars,protein,potassium,total_fat
2,2,chipotle_chicken_burrito_bowl,item_66a6aa38b02d47208ed7141199aec1e1,Chicken Burrito Bowl,Chipotle,"[Mexican, Latin American, Tex-Mex]","[High Protein, Low Carb, Low Calorie, Low Sugar]",{},8.50,1.684,...,4 oz,190,115,370,1,0,1,32,0,7
13,13,chipotle_carnitas_burrito_bowl,item_fd10bd13d53e4e8bac079cce1f0e5241,Carnitas Burrito Bowl,Chipotle,"[Mexican, Latin American, Tex-Mex]","[High Protein, Low Carb, Low Calorie, High Sod...",{},8.75,1.421,...,4 oz,190,70,540,1,0,0,27,0,8
16,16,chipotle_sofritas_burrito_bowl,item_fd57cee6af6a41398259e3fdc845250f,Sofritas Burrito Bowl,Chipotle,"[Mexican, Latin American, Tex-Mex]","[Low Carb, High Fat, Low Calorie, High Sodium,...",{},7.50,0.552,...,4 oz,145,0,555,9,4,5,8,0,10
26,26,chipotle_plant_based_chorizo_burrito_bowl,item_fd40403bbb2249ee9778ca1b23418fea,Plant Based Chorizo Burrito Bowl,Chipotle,"[Mexican, Latin American, Tex-Mex]","[Low Carb, Low Calorie, High Sodium, Low Sugar]",{},10.50,0.727,...,1 bowl,220,0,690,16,6,1,16,0,8
30,30,chipotle_barbacoa_burrito_bowl,item_e74b9bbd0a054a80bf7b3a4d09d01213,Barbacoa Burrito Bowl,Chipotle,"[Mexican, Latin American, Tex-Mex]","[High Protein, Low Carb, Low Calorie, High Sod...",{},9.50,1.412,...,4 oz,170,60,510,2,0,1,24,0,7
34,34,chipotle_carne_asada_burrito_bowl,item_648ecf06e0a5471ea24f7ed7a08b0c40,Carne Asada Burrito Bowl,Chipotle,"[Mexican, Latin American, Tex-Mex]","[High Protein, Low Carb, High Fat, Low Calorie...",{},10.50,1.160,...,1 bowl,250,90,740,1,0,0,29,0,14
38,38,chipotle_steak_burrito_bowl,item_68f66e0f17e44a94948d5a826296a40d,Steak Burrito Bowl,Chipotle,"[Mexican, Latin American, Tex-Mex]","[High Protein, Low Carb, Low Calorie, Low Sugar]",{},8.50,1.579,...,4 oz,190,65,320,2,0,1,30,0,7

In [11]:
# looking at nutrition info for each item to get a better feel for what is in it
# e.g. Chicken Burrito Bowl
print("Chicken Burrito Bowl")
print(f"Description: {df_chipotle.loc[2, 'ai_description']}")
print(f"Protein: {df_chipotle.loc[2, 'protein']}")
print(f"Calories: {df_chipotle.loc[2, 'calories']}\n")

# e.g. Carnitas Burrito Bowl
print("Carnitas Burrito Bowl")
print(f"Description: {df_chipotle.loc[13, 'ai_description']}")
print(f"Protein: {df_chipotle.loc[13, 'protein']}")
print(f"Calories: {df_chipotle.loc[13, 'calories']}\n")

# e.g. Chicken Quesadilla
print("Chicken Quesadilla")
print(f"Protein: {df_chipotle.loc[43, 'protein']}")
print(f"Calories: {df_chipotle.loc[43, 'calories']}\n")

Chicken Burrito Bowl
Description: Savor a hearty Chicken Burrito Bowl, featuring tender grilled chicken, zesty cilantro-lime rice, fresh salsas, and protein-packed black beans for a satisfying meal.
Protein: 32
Calories: 190

Carnitas Burrito Bowl
Description: Savor the tender, slow-cooked carnitas nestled atop a vibrant bed of cilantro-lime rice, black beans, and zesty toppings for a protein-packed delight.
Protein: 27
Calories: 190

Chicken Quesadilla
Protein: 58
Calories: 830

Breaking down contents of items in Chipotle:
- Looking at the calorie count for a "Burrito Bowl" and referencing the online Chipotle menu, each item appears to only account for the protein itself. The item does not contain any rice, beans, or other add-ons yet.
- Similarly, "Burritos" are most likely just the protein + tortilla. I assume other categories follow a similar pattern.
- "Lifestyle Bowls" are pre-made and complete bowls.
- sidenote: all "Tacos" have a serving size of 3.

### Some Thoughts After Exploring Data

Issue 1: broader categories like "Kid's Meal" and "Breakfast" in Chick fil A contain items that may be from different categories.
- I'm just going to hard code the differences for this example
    - most items in "Breakfast" category can probably be an "Entree" (with the exception of hash browns)
    - items in the "Kid's Meal" are an entree if they have the word "meal" in the name, "milk" for beverage, and the rest would be sides

Issue 2: when computing combinations in the future, should we try to account for 'realistic' combinations?
- If you order a salad, you would probably want salad dressing to go with it. Blindly assigning meals + sides/add-ons won't always be 'realistic'
- Most likely, you wouldn't want to have salad dressing as an add-on when you ordered a chicken sandwich.

Issue 3: "Build-your-own" restaurants (Chipotle) don't exactly map to the 5 categories
- Possible idea: rather than starting off as an "Entree", each item could instead be labeled as a "Base." A "Base" might require that certain conditions are met before it becomes an "Entree." However, this might be hard to generalize:
    - For example, a Burrito Bowl isn't a bowl yet if it contains only protein.
    - A Burrito is basically still a Taco (tortilla + protein) until you add more toppings.
    - However, a user could possibly be satisfied with a Taco being purely tortilla + protein.

## Assign Meal Categories (Entree, Side, Drink, Dessert, Add-on)
Note: this is hard-coded just to have categories to work with.

### Chick-fil-A

In [12]:
# add a column for meal categories
df_cfa['meal_category'] = 'temp'

# assign meal categories
# note: hard-coded assignment

cfa_entree_categories = ['Classic Chicken', 'Breakfast', 'Cool Wraps', 'Salads', ]
df_cfa.loc[df_cfa['category'].isin(cfa_entree_categories), 'meal_category'] = 'Entree'

df_cfa.loc[df_cfa['category'] == 'Sides', 'meal_category'] = 'Side'

df_cfa.loc[df_cfa['category'] == 'Beverages', 'meal_category'] = 'Drink'

df_cfa.loc[df_cfa['category'] == 'Desserts', 'meal_category'] = 'Dessert'

addon_categories = ['Salad Dressings', 'Sauces']
df_cfa.loc[df_cfa['category'].isin(addon_categories), 'meal_category'] = 'Add-on'

# assigning some categories manually
df_cfa.loc[90, 'meal_category'] = 'Side' # hash brown

kid_mask = df_cfa['category'] == "Kid's Meal"
df_cfa.loc[kid_mask & df_cfa['menu_item_name'].str.contains('Meal', case=False, na=False),'meal_category'] = 'Entree'
df_cfa.loc[kid_mask & df_cfa['menu_item_name'].str.contains('Milk', case=False, na=False),'meal_category'] = 'Drink'
df_cfa.loc[kid_mask & ~df_cfa['menu_item_name'].str.contains('Meal|Milk', case=False, na=False),'meal_category'] = 'Side'

In [13]:
# check that all items got assigned a category
display(df_cfa.loc[df_cfa['meal_category'] == 'temp'])

Empty DataFrame
Columns: [index, item_id, menu_item_id, menu_item_name, restaurant_name, cuisine_type, macronutrient_profile, recipe_items, price, golden_ratio, ai_description, category, allergen_info, menu_card_image, serving_size, calories, cholesterol, sodium, total_carbohydrates, dietary_fiber, sugars, protein, potassium, total_fat, meal_category]
Index: []

[0 rows x 25 columns]

Sorting the menu items for CFA by category:

In [14]:
cfa_entrees = df_cfa.loc[df_cfa['meal_category'] == 'Entree'].copy()
cfa_sides = df_cfa.loc[df_cfa['meal_category'] == 'Side'].copy()
cfa_drinks = df_cfa.loc[df_cfa['meal_category'] == 'Drink'].copy()
cfa_desserts = df_cfa.loc[df_cfa['meal_category'] == 'Dessert'].copy()
cfa_addons = df_cfa.loc[df_cfa['meal_category'] == 'Add-on'].copy()

print(f"Count of Entrees: {len(cfa_entrees)}")
print(f"Count of Sides: {len(cfa_sides)}")
print(f"Count of Drinks: {len(cfa_drinks)}")
print(f"Count of Desserts: {len(cfa_desserts)}")
print(f"Count of Add-Ons: {len(cfa_addons)}")

Count of Entrees: 76
Count of Sides: 19
Count of Drinks: 43
Count of Desserts: 24
Count of Add-Ons: 15

### Taco Bell

Items of concern:
- Cheesy roll up in 'Specialties': not sufficient to be an entree
- Cinnabon Delights (2, 4, and 12 pc): I will put in "Dessert" for now

In [15]:
# add a column for meal categories
df_tb['meal_category'] = 'temp'

tb_entree_categories = ['Burritos', 'Tacos', 'Breakfast', 'Cantina Chicken','Chalupas', 'Nachos', 'Specialties']
df_tb.loc[df_tb['category'].isin(tb_entree_categories), 'meal_category'] = 'Entree'

df_tb.loc[df_tb['category'] == 'Sides', 'meal_category'] = 'Side'

df_tb.loc[df_tb['category'] == 'Beverages', 'meal_category'] = 'Drink'

df_tb.loc[df_tb['category'] == "Condiments & Sauces", 'meal_category'] = 'Add-on'

# manual assignments
df_tb.loc[91, 'meal_category'] = 'Side'     # hash brown
df_tb.loc[194, 'meal_category'] = 'Side'    # cheesy roll up
df_tb.loc[df_tb['menu_item_name'] == "Cinnabon Delights", 'meal_category'] = 'Dessert'

In [16]:
# check that all items got assigned a category
display(df_tb.loc[df_tb['meal_category'] == 'temp'])

Empty DataFrame
Columns: [index, item_id, menu_item_id, menu_item_name, restaurant_name, cuisine_type, macronutrient_profile, recipe_items, price, golden_ratio, ai_description, category, allergen_info, menu_card_image, serving_size, calories, cholesterol, sodium, total_carbohydrates, dietary_fiber, sugars, protein, potassium, total_fat, meal_category]
Index: []

[0 rows x 25 columns]

Sorting the menu items for Taco Bell by category:

In [17]:
tb_entrees = df_tb.loc[df_tb['meal_category'] == 'Entree'].copy()
tb_sides = df_tb.loc[df_tb['meal_category'] == 'Side'].copy()
tb_drinks = df_tb.loc[df_tb['meal_category'] == 'Drink'].copy()
tb_desserts = df_tb.loc[df_tb['meal_category'] == 'Dessert'].copy()
tb_addons = df_tb.loc[df_tb['meal_category'] == 'Add-on'].copy()

print(f"Count of Entrees: {len(tb_entrees)}")
print(f"Count of Sides: {len(tb_sides)}")
print(f"Count of Drinks: {len(tb_drinks)}")
print(f"Count of Desserts: {len(tb_desserts)}")
print(f"Count of Add-Ons: {len(tb_addons)}")

Count of Entrees: 75
Count of Sides: 16
Count of Drinks: 87
Count of Desserts: 3
Count of Add-Ons: 24

### Chipotle: TBD

## Meal Combination Storage and Computation Ideas

1. Knapsack Approach
    - 0/1 Knapsack problem: 
            
        _"Given two arrays, `profit[]` and `weight[]`, where each element represents the profit and weight of an item respectively, also given an integer `W` representing the maximum capacity of the knapsack (the total weight it can hold)._
        
        _Put the items into the knapsack such that the sum of profits associated with them is the maximum possible, without exceeding the capacity W."_
        
        (https://www.geeksforgeeks.org/dsa/0-1-knapsack-problem-dp-10/)
    - Concern:
        - Knapsack tries to maximize a single value from a pool of items and returns a best solution. We want to hit targets (protein, calories, price) without losing structure to meals (maintain rules with categories).
        - We want to have multiple top picks and rank results. We would have to adjust knapsack to give best k results.
        - Overall, knapsack on its own may not be sufficient for meal building. However, it may have a use when trying to maximize leftover calories.

2. Meal Precomputation
    - Storing every single meal combination is inefficient
    - Recomputing every single meal after a user request is also inefficient
    - Another note: allowing for multiple entrees (maybe max 2-3) can allow for goals to be hit quicker. 
    - Hybrid architecture idea:
        1. Precompute entree combinations. Store UID, item IDs, protein total, calorie total, price total
        2. Filter dynamically after user interaction. Use boolean masking/vectorization (quick) to filter for acceptable protein, price, and calorie ranges.
        3. Add on optional sides or drinks (add-ons can come in later).
        4. Apply scoring algorithm.
    - Expansion: add some sort of caching mechanism for common presets

    - Edits to this approach: _all_ entree combinations may also explode as system grows. We can possibly filter down "unreasonable" combinations to reduce storage.

### Entree Precomputation
It is useful to adjust the storage of the entrees before calculating their combinations.

In [18]:
import itertools

# note: since item_ids and menu_item_ids have duplicates for variations of an item, we are using the index as a placeholder for an ID
cfa_entrees_dict = cfa_entrees[["index", "menu_item_name", "price", "calories", "protein", "serving_size"]].to_dict("records")

# these are based on the filters within Eatery
MAX_PRICE = 100.0
MAX_CALORIES = 3000   
MAX_PROTEIN = 150

# max_count sets how many entrees you want to combine
def calculate_entree_combos(entrees, max_count=2):
    entree_combos = []
    combo_id = 1    # change id numbering later, maybe

    for k in range(1, max_count+1):
        for combo in itertools.combinations_with_replacement(entrees, k):
            # calculate totals
            total_price = sum(item['price'] for item in combo)
            total_calories = sum(item['calories'] for item in combo)
            total_protein = sum(item['protein'] for item in combo)


            if total_price > MAX_PRICE:
                continue
            if total_calories > MAX_CALORIES:
                continue
            if total_price > MAX_PRICE:
                continue

            entree_combos.append({
                "combo_id": combo_id,
                "entree_ids": tuple(item['index'] for item in combo),
                "entree_names": tuple(item['menu_item_name'] for item in combo),
                "n_entrees": k,
                "price": total_price,
                "calories": total_calories,
                "protein": total_protein,
                "serving_size_per_item": tuple(item['serving_size'] for item in combo)
            })

            combo_id += 1
    
    return pd.DataFrame(entree_combos)

In [19]:
def display_entree_combo(row_entry):
    print(f"Combo ID is {row_entry['combo_id']}")
    print(f"There are {row_entry['n_entrees']} entrees in this combo: {row_entry['entree_names']}")
    print(f"Total price is: {row_entry['price']}")
    print(f"Total calories are: {row_entry['calories']}")
    print(f"Total protein is: {row_entry['protein']}\n")

Testing the computation on Chick-fil-A:

In [20]:
cfa_entree_combos = calculate_entree_combos(cfa_entrees_dict)

In [21]:
display(cfa_entree_combos)

,combo_id,entree_ids,entree_names,n_entrees,price,calories,protein,serving_size_per_item
0,1,"(0,)","(Chick-n-Strips,)",1,4.29,200,19,"(2 strips,)"
1,2,"(1,)","(Chicken Nuggets,)",1,3.49,130,13,"(4 nuggets,)"
2,3,"(2,)","(Chicken Nuggets,)",1,4.99,250,27,"(8 nuggets,)"
3,4,"(3,)","(Chicken Nuggets,)",1,14.99,970,103,"(30 nuggets,)"
4,5,"(4,)","(Chick-n-Strips,)",1,6.99,410,39,"(4 strips,)"
...,...,...,...,...,...,...,...,...
2997,2998,"(170, 171)","(Spicy Southwest Salad, Spicy Southwest Salad)",2,21.98,1080,80,"(1 salad, 1 salad)"
2998,2999,"(170, 172)","(Spicy Southwest Salad, Spicy Southwest Salad)",2,21.98,1250,84,"(1 salad, 1 salad)"
2999,3000,"(171, 171)","(Spicy Southwest Salad, Spicy Southwest Salad)",2,21.98,960,78,"(1 salad, 1 salad)"
3000,3001,"(171, 172)","(Spicy Southwest Salad, Spicy Southwest Salad)",2,21.98,1130,82,"(1 salad, 1 salad)"
3001,3002,"(172, 172)","(Spicy Southwest Salad, Spicy Southwest Salad)",2,21.98,1300,86,"(1 salad, 1 salad)"

Display a few combinations from Chick-fil-A:

In [22]:
display_entree_combo(cfa_entree_combos.loc[0])
display_entree_combo(cfa_entree_combos.loc[1000])
display_entree_combo(cfa_entree_combos.loc[2900])

Combo ID is 1
There are 1 entrees in this combo: ('Chick-n-Strips',)
Total price is: 4.29
Total calories are: 200
Total protein is: 19

Combo ID is 1001
There are 2 entrees in this combo: ('Smokehouse BBQ Bacon Sandwich', 'Hash Brown Scramble Burrito')
Total price is: 11.98
Total calories are: 1300
Total protein is: 71

Combo ID is 2901
There are 2 entrees in this combo: ('Market Salad', 'Spicy Southwest Salad')
Total price is: 20.98
Total calories are: 770
Total protein is: 62

Some notes:
- This is still not accounting for variations of an item. For example, this blind combination will combine a 4pc nugget with a 8pc nugget.

### Adding Side or Drink

Exploring adding on sides or drinks to entrees, entree combos, or other meal combinations. Taking the hybrid approach, this will occur after a user has interacted with the system. 

General flow for adding on sides/drinks:
1. Filter based on user constraints.
    - Calculate totals for price, calories, and protein from the input
    - Calculate remaining room for each target category based on the input 
         - e.g. `remaining_price = target_price - input_price`
    - Only take candidate items that are less than or equal to the remaining room plus a tolerance 
        - e.g. `item_price <= (remaining_price + price_tolerance)`
2. Build combinations
    - For each item in the candidate results, combine it with the input and calculate totals for each constraint category.

Later, the resulting combinations can be checked to see if they fall within the acceptable tolerance range for each constraint category. This can be used during scoring and ranking.

### Building a "Full Meal"

To simplify things, we'll define a "full meal" as a combination containing Entree(s), Side, and Drink. We are also accounting for the fact that a user may want to build a full meal for a seed item that is not necessarily an Entree. Whether the input is an Entree, Side, or Drink, it should be expanded until it contains items from each category.

Flow:
1. Evaluate current state of input and check for missing categories
2. Expand each category:
    - Filter candidates
    - Generate expanded meals -> partial meal
        - Early pruning: score in between and remove unreasonable choices, keep top k results. This helps prevent combinatorial explosion.
    - Repeat for missing categories

Final outputs are ranked again after the full meal is built. In the case that a user starts with a Entree seed, add an additional layer to retrieve all entree combos that contain that item.

In the future, this will need to be expanded to additional categories (e.g. add-ons). These ideas are also for the assumption of restaurants that do not follow the "build-your-own" style.

In [69]:
import math
import numpy as np
import copy

# represent user-chosen constraints
USER_PRICE = 14.00
USER_CAL = 800
USER_PROTEIN = 20

# represent tolerance values
PRICE_TOL = round(USER_PRICE * 0.20, 2)
CAL_TOL = math.ceil(USER_CAL * 0.10)
PROTEIN_TOL = math.ceil(USER_PROTEIN * 0.30)

# represent weights (will be dependent on the user)
W_PRICE = 0.20
W_CAL = 0.40
W_PROTEIN = 0.40

# get all entree combos that contain a specific entree seed
def get_entree_combos(seed_id, df_entree_combos, is_entree):
    if is_entree:
        mask = df_entree_combos['entree_ids'].apply(lambda ids: seed_id in ids)
        return df_entree_combos[mask]
    else:
        return df_entree_combos

def get_cand_items(seed_id, category, df_entree_combos=None, df_sides=None, df_drinks=None, is_entree=False):
    if category == 'Entree':
        return get_entree_combos(seed_id, df_entree_combos, is_entree)
    elif category == 'Side':
        return df_sides
    elif category == 'Drink':
        return df_drinks
    
def intermediate_prune(meals, k=50):
    scores = []
    for meal in meals:
        price_penalty = max(0, meal['total_price'] - USER_PRICE)
        cal_dev = abs(meal['total_cal'] - USER_CAL)
        protein_dev = abs(meal['total_protein'] - USER_PROTEIN)

        score = W_PRICE * price_penalty + W_CAL * cal_dev + W_PROTEIN * protein_dev

        scores.append(score)
    
    scores = np.array(scores)
    sorted_indices = scores.argsort()
    top_k_indices = sorted_indices[:k]
    
    return [meals[i] for i in top_k_indices]

def build_meal(seed_id, required_categories, df_restaurant, df_entree_combos=None, df_sides=None, df_drinks=None, build_full=True):
    seed_item = df_restaurant.loc[seed_id].to_dict()

    current_meals = []

    is_entree = (seed_item.get('meal_category') == 'Entree')

     # if the item is an entree, get all entree combos
    if is_entree and build_full:
        candidate_entrees = get_entree_combos(seed_id, df_entree_combos, is_entree)
        for _, combo in candidate_entrees.iterrows():
            meal_state = {
                'item_ids': list(combo['entree_ids']),
                'total_price': combo['price'],
                'total_cal': combo['calories'],
                'total_protein': combo['protein'],
                'filled_categories': {'Entree'}
            }
            current_meals.append(meal_state)
    else:
        meal_state = {
            'item_ids': [seed_id],
            'total_price': seed_item.get('price'),
            'total_cal': seed_item.get('calories'),
            'total_protein': seed_item.get('protein'),
            'filled_categories': {seed_item.get('meal_category')}
        }
        current_meals.append(meal_state)

    missing_categories = required_categories - current_meals[0].get('filled_categories')

    for category in missing_categories:
        new_meals = []
        
        for meal in current_meals:
            cand_items = get_cand_items(seed_id=seed_id, category=category, 
                                        df_entree_combos=df_entree_combos, 
                                        df_sides=df_sides, 
                                        df_drinks=df_drinks, 
                                        is_entree=is_entree)

            cand_items = cand_items[
                (meal['total_price'] + cand_items['price'] <= USER_PRICE + PRICE_TOL) &
                (meal['total_cal'] + cand_items['calories'] <= USER_CAL + CAL_TOL)
            ]

            for _, item in cand_items.iterrows():
                new_meal = copy.deepcopy(meal)
                
                if category == 'Entree':
                    new_meal['item_ids'].extend(item['entree_ids'])
                else:
                    new_meal['item_ids'].append(item['index'])
                
                new_meal['total_price'] += item['price']
                new_meal['total_cal'] += item['calories']
                new_meal['total_protein'] += item['protein']
                new_meal['filled_categories'].add(category)

                new_meal['total_price'] = round(new_meal['total_price'], 2)
                new_meals.append(new_meal)

        current_meals = intermediate_prune(new_meals)
    
    return current_meals

In [29]:
# some functions for visualization
def get_item_name(df_restaurant, id):
    return df_restaurant.loc[id, 'menu_item_name']

def display_meal(df_restaurant, meal):
    item_names = [get_item_name(df_restaurant, id) for id in meal['item_ids']]
    print(f"Items in this meal: {item_names}")
    print(f"Total price: ${meal['total_price']}")
    print(f"Total calories: {meal['total_cal']}")
    print(f"Total_protein: {meal['total_protein']}\n")

#### Tests

In [66]:
# categories needed for a full meal
required_categories = {'Entree', 'Side', 'Drink'}

# Chick-fil-A Entree

print(f"Chosen constraints were:\nPrice: {USER_PRICE}\nCalories: {USER_CAL}\nProtein: {USER_PROTEIN}\n")

print(f"Testing on Chick-fil-A item {get_item_name(df_cfa, 4)}")

results_cfa = build_meal(4, required_categories, df_cfa, cfa_entree_combos, cfa_sides, cfa_drinks)

for i in range(0,3):
    display_meal(df_cfa, results_cfa[i])

Chosen constraints were:
Price: 14.0
Calories: 800
Protein: 20

Testing on Chick-fil-A item Chick-n-Strips
Items in this meal: ['Chick-n-Strips', 'Hot Buttered Biscuit', 'Fruit Cup', 'Diet Lemonade']
Total price: $16.26
Total calories: 800
Total_protein: 44

Items in this meal: ['Chick-n-Strips', 'English Muffin', 'Waffle Potato Chips', 'Diet Lemonade']
Total price: $14.96
Total calories: 800
Total_protein: 47

Items in this meal: ['Chick-n-Strips', 'Hot Buttered Biscuit', 'Fruit Cup', 'Apple Juice Box']
Total price: $15.46
Total calories: 795
Total_protein: 44

In [ ]:
# test on Taco Bell Entree
# compute Taco Bell Entree combos
tb_entrees_dict = tb_entrees[["index", "menu_item_name", "price", "calories", "protein", "serving_size"]].to_dict("records")
tb_entree_combos = calculate_entree_combos(tb_entrees_dict)

print(f"Chosen constraints were:\nPrice: {USER_PRICE}\nCalories: {USER_CAL}\nProtein: {USER_PROTEIN}\n")

print(f"Testing on Taco Bell item {get_item_name(df_tb, 200)}")

results_tb = build_meal(200, required_categories, df_tb, tb_entree_combos, tb_sides, tb_drinks)

for i in range(0,3):
    display_meal(df_tb, results_tb[i])

Chosen constraints were:
Price: 14.0
Calories: 800
Protein: 20

Testing on Taco Bell item Crunchwrap Supreme
Items in this meal: ['Crunchwrap Supreme', 'Black Beans & Rice', 'Brisk Mango Fiesta']
Total price: $8.97
Total calories: 800
Total_protein: 20

Items in this meal: ['Crunchwrap Supreme', 'Chips and Nacho Cheese Sauce', 'Gatorade G2 Fruit Punch']
Total price: $8.97
Total calories: 800
Total_protein: 18

Items in this meal: ['Crunchwrap Supreme', 'Cinnamon Twists', 'Brisk Mango Fiesta']
Total price: $7.97
Total calories: 800
Total_protein: 17

In [67]:
# test on CFA Side
print(f"Chosen constraints were:\nPrice: {USER_PRICE}\nCalories: {USER_CAL}\nProtein: {USER_PROTEIN}\n")

print(f"Testing on Chick-fil-A item {get_item_name(df_cfa, 90)}")

results_cfa_2 = build_meal(90, required_categories, df_cfa, cfa_entree_combos, cfa_sides, cfa_drinks)

for i in range(0,3):
    display_meal(df_cfa, results_cfa_2[i])

Chosen constraints were:
Price: 14.0
Calories: 800
Protein: 20

Testing on Chick-fil-A item Hash Browns
Items in this meal: ['Hash Browns', 'Yogurt Parfait w/ Cookie Cumbs', 'Yogurt Parfait with Harvest Nut Granola', 'Dasani Bottled Water']
Total price: $14.96
Total calories: 800
Total_protein: 28

Items in this meal: ['Hash Browns', 'Yogurt Parfait w/ Cookie Cumbs', 'Yogurt Parfait with Harvest Nut Granola', 'Diet Coke']
Total price: $15.16
Total calories: 800
Total_protein: 28

Items in this meal: ['Hash Browns', 'Yogurt Parfait w/ Cookie Cumbs', 'Yogurt Parfait with Harvest Nut Granola', 'Diet Coke']
Total price: $15.22
Total calories: 800
Total_protein: 28

In [ ]:
# try adding just a side to an entree item--this mimics the ADD_SIDE template
entree_and_side = {"Entree", "Side"}

print(f"Chosen constraints were:\nPrice: {USER_PRICE}\nCalories: {USER_CAL}\nProtein: {USER_PROTEIN}\n")

print(f"Testing on Taco Bell item {get_item_name(df_tb, 121)}")

tb_add_side_results = build_meal(121, entree_and_side, df_tb, df_sides=tb_sides, build_full=False)

for i in range(0,3):
    display_meal(df_tb, tb_add_side_results[i])

Chosen constraints were:
Price: 14.0
Calories: 800
Protein: 20

Testing on Taco Bell item Caliente Cantina Chicken Crispy Taco
Items in this meal: ['Caliente Cantina Chicken Crispy Taco', 'Nacho Fries']
Total price: $6.98
Total calories: 760
Total_protein: 21

Items in this meal: ['Caliente Cantina Chicken Crispy Taco', 'Loaded Steak and Jalapeno Fries']
Total price: $6.98
Total calories: 760
Total_protein: 28

Items in this meal: ['Caliente Cantina Chicken Crispy Taco', 'Nacho Fries']
Total price: $5.98
Total calories: 620
Total_protein: 19

In [72]:
# try adding just a drink to an entree item
entree_and_side = {"Entree", "Drink"}

print(f"Chosen constraints were:\nPrice: {USER_PRICE}\nCalories: {USER_CAL}\nProtein: {USER_PROTEIN}\n")

print(f"Testing on Taco Bell item {get_item_name(df_tb, 121)}")

tb_add_drink_results = build_meal(121, entree_and_side, df_tb, df_drinks=tb_drinks, build_full=False)

for i in range(0,3):
    display_meal(df_tb, tb_add_drink_results[i])

Chosen constraints were:
Price: 14.0
Calories: 800
Protein: 20

Testing on Taco Bell item Caliente Cantina Chicken Crispy Taco
Items in this meal: ['Caliente Cantina Chicken Crispy Taco', 'Dr Pepper']
Total price: $5.98
Total calories: 790
Total_protein: 15

Items in this meal: ['Caliente Cantina Chicken Crispy Taco', 'Tropicana Pink Lemonade']
Total price: $6.98
Total calories: 790
Total_protein: 15

Items in this meal: ['Caliente Cantina Chicken Crispy Taco', 'Mug Root Beer']
Total price: $5.98
Total calories: 790
Total_protein: 15

Notes: 
- Protein was too limiting for a hard constraint. Users may also want to treat protein targets as minimums rather than maximums.
- Results are still not ranked overall for user constraints and preferences. Results may still seem slightly 'unreasonable' or less than ideal.
- Some results may only make sense in a certain context. Specifically, meals with breakfast items would only be ordered during the set breakfast menu times.